// areagen writes the TypeScript view of `internal/areas`.
//
// ── WHY A GENERATOR AND NOT A FETCH ─────────────────────────────────────────
//
// The browser needs the declarations to render a generated page at all: which
// tables an area has, which columns, and in what order. It could ask the server
// for them, and that would be one more round trip before the first paint, on a
// table that changes when the binary changes and at no other time.
//
// Generated, it is a compile-time constant in the bundle, and a declaration added
// in Go that the TypeScript has not seen turns the BUILD red rather than
// rendering a page with no columns. `-check` runs in tools/verify.sh.
//
// ── WHAT IT DOES NOT EXPORT ─────────────────────────────────────────────────
//
// The poll interval, the resource's fields and its guards stay on the server.
// The page renders rows the collector sends and writes through the resource
// engine, which fetches the form schema itself — so the browser needs the SHAPE
// of a page, not a second copy of the registry.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"mikrodash/internal/areas"
	"mikrodash/internal/resource"
)

const (
	outRel = "web/src/gen/areas.ts"
	// uiDir is where cmd/webbuild looks for each page's markup. An area's shell
	// is generated there too: a page with no hand-written file is the point, and
	// `webbuild` hard-errors on a page key with no markup.
	uiDir = "web/src/ui"
)

func main() {
	out := flag.String("out", outRel, "file to write")
	check := flag.Bool("check", false, "fail if the committed file is stale instead of writing it")
	flag.Parse()

	body := render()
	markup := renderMarkup()

	if *check {
		for _, m := range markup {
			have, err := os.ReadFile(m.path)
			if err != nil {
				fmt.Fprintf(os.Stderr, "areagen: %s is missing; run `go run ./cmd/areagen`\n", m.path)
				os.Exit(1)
			}
			if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(m.body)) {
				fmt.Fprintf(os.Stderr, "areagen: %s is STALE — run `go run ./cmd/areagen`\n", m.path)
				os.Exit(1)
			}
		}
		have, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "areagen: %s is missing; run `go run ./cmd/areagen`\n", *out)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(body)) {
			fmt.Fprintf(os.Stderr, "areagen: %s is STALE — an area declaration changed and the "+
				"TypeScript was not regenerated.\nRun: go run ./cmd/areagen\n", *out)
			os.Exit(1)
		}
		fmt.Printf("areagen: %s is current (%d areas)\n", *out, len(areas.All()))
		return
	}

	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "areagen:", err)
		os.Exit(1)
	}
	for _, m := range markup {
		if err := os.WriteFile(m.path, m.body, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "areagen:", err)
			os.Exit(1)
		}
	}
	fmt.Printf("areagen: wrote %s and %d page shell(s) — %d areas\n", *out, len(markup), len(areas.All()))
}

type page struct {
	path string
	body []byte
}

// renderMarkup writes each area's page shell: a card with a header, a badge, the
// Add slot and an empty body the renderer fills.
//
// ── THE HEADER IS THE ROUTING PAGE'S ────────────────────────────────────────
//
// Tabs at top left with the title beside them, as the hand-built Routing page
// lays out its protocol tabs and table name (`.rttab-bar`, which drops the
// standalone bar's rule and centres its buttons on the title), and the Add
// button alone in the right-hand corner where every older page keeps its
// actions. A one-table area's strip is empty and `.rttab-bar:empty` hides it,
// so the title does not sit indented behind a tab bar that is not there.
//
// ── A SHELL, NOT A TABLE ────────────────────────────────────────────────────
//
// The columns, the tabs and the rows are `web/src/pages/area.ts`'s, because they
// are the declaration's and the payload's. Putting them here would be a second
// place to change when a column moves, and the one nobody regenerates.
func renderMarkup() []page {
	out := make([]page, 0, len(areas.All()))
	for _, a := range areas.All() {
		var b strings.Builder
		fmt.Fprintf(&b, `  <!-- GENERATED by cmd/areagen — do not edit. The area %s, declared in
       internal/areas and rendered by web/src/pages/area.ts. -->
  <div class="page-view" id="page-%s">
    <div class="container-fluid px-0" style="width:100%%">
      <div class="card" id="areaCard-%s">
        <div class="stale-overlay">&#9679; stale</div>
        <div class="card-header d-flex align-items-center justify-content-between flex-wrap gap-2">
          <div class="d-flex align-items-center gap-2">
            <span id="areaTabs-%s" class="stab-bar rttab-bar" role="tablist"></span>
            <h3 class="card-title mb-0">%s</h3>
            <span id="areaBadge-%s" class="card-badge">0</span>
          </div>
          <div class="hdr-actions d-flex align-items-center gap-2">
            <span id="areaAdd-%s"></span>
          </div>
        </div>
        <div class="card-body p-0">
          <div class="data-scroll" style="max-height:640px;overflow-y:auto" id="areaBody-%s">
            <div class="empty-state">Waiting&hellip;</div>
          </div>
        </div>
      </div>
    </div>
  </div>
`, a.Key, a.Key, a.Key, a.Key, htmlEscape(a.Title), a.Key, a.Key, a.Key)
		out = append(out, page{path: uiDir + "/page-" + a.Key + ".html", body: []byte(b.String())})
	}
	return out
}

// htmlEscape is the four characters that matter in a title. Titles are declared
// in Go and never come from a router, so this is belt and braces rather than the
// load-bearing escape — `web/src/dom.ts`'s `esc` is that, for everything the page
// renders at runtime.
func htmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

func render() []byte {
	var b strings.Builder
	b.WriteString(`// GENERATED by cmd/areagen — do not edit.
//
// The generated pages, from internal/areas. One module renders all of them
// (web/src/pages/area.ts); this is the declaration it renders FROM.
//
// A key is a page key, so it is the URL, the markup id and the room the areas
// collector emits to — the same three things a hand-built page's key is.

export interface AreaTable {
  /** The resource registry key: what the rows are, and what a write goes through. */
  resource: string;
  /** Tab label. The resource's own label when the declaration gave none. */
  title: string;
  /** Field names, in the order the table shows them. */
  columns: readonly string[];
  /** Row order is meaningful (the resource is Ordered): the page draws reorder
   *  arrows, and the table does not sort, because the first match decides. */
  ordered: boolean;
  /** The columns drawn as coloured pill labels, by kind (internal/areas'
   *  Pills, with its CommonPills applied). A column absent is plain text. */
  pills: Readonly<Record<string, PillKind>>;
}

export interface Area {
  /** URL path, markup id and room name. */
  key: string;
  title: string;
  /** One of the shell's nav groups. */
  navGroup: string;
  /** The nav entry's icon: inner markup of a 24×24 SVG, declared in Go. It
   *  reaches innerHTML, which is safe only because it is a build-time constant
   *  and never router data. */
  icon: string;
  tables: readonly AreaTable[];
}

`)
	// THE KINDS ARE GO'S LIST, emitted as a union: area.ts keys its colours by
	// this type, so a kind added on one side and not the other fails tsc.
	kinds := make([]string, 0, len(areas.PillKinds))
	for _, k := range areas.PillKinds {
		kinds = append(kinds, strconv.Quote(k))
	}
	fmt.Fprintf(&b, "/** How a column's values are drawn as pills: internal/areas.PillKinds. */\nexport type PillKind = %s;\n\nexport const AREAS: readonly Area[] = [\n",
		strings.Join(kinds, " | "))
	for _, a := range areas.All() {
		fmt.Fprintf(&b, "  {\n    key: %s, title: %s, navGroup: %s,\n    icon: %s,\n    tables: [\n",
			strconv.Quote(a.Key), strconv.Quote(a.Title), strconv.Quote(a.NavGroup), strconv.Quote(a.Icon))
		for _, t := range a.Tables {
			// THE TITLE IS RESOLVED HERE, not left for the browser: an empty one
			// in the declaration means "the resource's own label", and the
			// browser has no registry to look that up in. Resolving it at
			// generation time keeps the fallback in one place — Go's — rather
			// than shipping a second copy of the labels.
			title := t.Title
			ordered := false
			if res := resource.ByKey(t.Resource); res != nil {
				if title == "" {
					title = res.Label
				}
				// ORDER IS THE RESOURCE'S FACT, carried here for the same reason
				// the title is: the browser has no registry to ask.
				ordered = res.Ordered
			}
			cols := make([]string, 0, len(t.Columns))
			for _, c := range t.Columns {
				cols = append(cols, strconv.Quote(c))
			}
			pills := []string{}
			for _, c := range t.Columns {
				if k := t.PillFor(c); k != "" {
					pills = append(pills, strconv.Quote(c)+": "+strconv.Quote(k))
				}
			}
			pillMap := "{}"
			if len(pills) > 0 {
				pillMap = "{ " + strings.Join(pills, ", ") + " }"
			}
			fmt.Fprintf(&b, "      { resource: %s, title: %s, columns: [%s], ordered: %t, pills: %s },\n",
				strconv.Quote(t.Resource), strconv.Quote(title), strings.Join(cols, ", "), ordered, pillMap)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString(`];

/** Every area's page key. */
export const AREA_KEY_SET: ReadonlySet<string> = new Set(AREAS.map((a) => a.key));

/** One area, or undefined. */
export function areaFor(key: string): Area | undefined {
  return AREAS.find((a) => a.key === key);
}
`)
	return []byte(b.String())
}
