// areagen writes the TypeScript view of `internal/areas`.
//
// ── WHY A GENERATOR AND NOT A FETCH ─────────────────────────────────────────
//
// The browser needs the declarations to render a generated page at all: which
// tables an area has, which columns, and in what order. It could ask the server
// for them, and that would be one more round trip before the first paint, on a
// table that changes when the binary changes and at no other time.
//
// Generated, it is a compile-time constant in the bundle, and a declaration added
// in Go that the TypeScript has not seen turns the BUILD red rather than
// rendering a page with no columns. `-check` runs in tools/verify.sh.
//
// ── WHAT IT DOES NOT EXPORT ─────────────────────────────────────────────────
//
// The poll interval, the resource's fields and its guards stay on the server.
// The page renders rows the collector sends and writes through the resource
// engine, which fetches the form schema itself — so the browser needs the SHAPE
// of a page, not a second copy of the registry.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"mikrodash/internal/areas"
	"mikrodash/internal/resource"
)

const outRel = "web/src/gen/areas.ts"

func main() {
	out := flag.String("out", outRel, "file to write")
	check := flag.Bool("check", false, "fail if the committed file is stale instead of writing it")
	flag.Parse()

	body := render()

	if *check {
		have, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "areagen: %s is missing; run `go run ./cmd/areagen`\n", *out)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(body)) {
			fmt.Fprintf(os.Stderr, "areagen: %s is STALE — an area declaration changed and the "+
				"TypeScript was not regenerated.\nRun: go run ./cmd/areagen\n", *out)
			os.Exit(1)
		}
		fmt.Printf("areagen: %s is current (%d areas)\n", *out, len(areas.All()))
		return
	}

	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "areagen:", err)
		os.Exit(1)
	}
	fmt.Printf("areagen: wrote %s — %d areas\n", *out, len(areas.All()))
}

func render() []byte {
	var b strings.Builder
	b.WriteString(`// GENERATED by cmd/areagen — do not edit.
//
// The generated pages, from internal/areas. One module renders all of them
// (web/src/pages/area.ts); this is the declaration it renders FROM.
//
// A key is a page key, so it is the URL, the markup id and the room the areas
// collector emits to — the same three things a hand-built page's key is.

export interface AreaTable {
  /** The resource registry key: what the rows are, and what a write goes through. */
  resource: string;
  /** Tab label. The resource's own label when the declaration gave none. */
  title: string;
  /** Field names, in the order the table shows them. */
  columns: readonly string[];
}

export interface Area {
  /** URL path, markup id and room name. */
  key: string;
  title: string;
  /** One of the shell's nav groups. */
  navGroup: string;
  tables: readonly AreaTable[];
}

export const AREAS: readonly Area[] = [
`)
	for _, a := range areas.All() {
		fmt.Fprintf(&b, "  {\n    key: %s, title: %s, navGroup: %s,\n    tables: [\n",
			strconv.Quote(a.Key), strconv.Quote(a.Title), strconv.Quote(a.NavGroup))
		for _, t := range a.Tables {
			// THE TITLE IS RESOLVED HERE, not left for the browser: an empty one
			// in the declaration means "the resource's own label", and the
			// browser has no registry to look that up in. Resolving it at
			// generation time keeps the fallback in one place — Go's — rather
			// than shipping a second copy of the labels.
			title := t.Title
			if title == "" {
				if res := resource.ByKey(t.Resource); res != nil {
					title = res.Label
				}
			}
			cols := make([]string, 0, len(t.Columns))
			for _, c := range t.Columns {
				cols = append(cols, strconv.Quote(c))
			}
			fmt.Fprintf(&b, "      { resource: %s, title: %s, columns: [%s] },\n",
				strconv.Quote(t.Resource), strconv.Quote(title), strings.Join(cols, ", "))
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString(`];

/** Every area's page key. */
export const AREA_KEY_SET: ReadonlySet<string> = new Set(AREAS.map((a) => a.key));

/** One area, or undefined. */
export function areaFor(key: string): Area | undefined {
  return AREAS.find((a) => a.key === key);
}
`)
	return []byte(b.String())
}
