// toolgen writes the record of what an assistant may call.
//
// ── WHAT IT GENERATES, AND WHY A FILE AT ALL ────────────────────────────────
//
// The catalogue itself is derived at runtime from `internal/aitools`, which
// derives it from the resource registry — so unlike the other generators here,
// nothing needs a generated copy in order to WORK. What the file buys is a
// reviewable record: the set of tools a model can call is a security surface,
// and a surface that changes silently when somebody adds a page is one nobody
// reviews.
//
// So this emits the tool NAMES with the resource and page each one reads, and
// `internal/verify` compares that record against the live registry in both
// directions. A resource added without a tool fails; a tool naming a resource
// that no longer exists fails; and a page-permission change on a tool shows up
// as a line in a diff rather than as nothing at all.
//
// Same shape as `cmd/gridgen` and `cmd/pagesgen`: `-out`, `-check`, build the
// body first and compare. A generator whose source is a committed Go file runs
// on a clean clone.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"mikrodash/internal/aitools"
)

const outRel = "testdata/ai-tools.json"

// record is one row of the artefact. Deliberately NOT the whole Tool: the
// description is prose that will be reworded often, and a file that churned on
// every wording change would stop being read.
type record struct {
	Name string `json:"name"`
	// Access is FIRST among the things a reviewer should notice. A tool moving
	// from read to write, or a new write tool appearing, is the whole character
	// of this feature changing, and it must be a line in a diff.
	Access   string `json:"access"`
	Resource string `json:"resource"`
	Page     string `json:"page"`
}

type artefact struct {
	Note  string   `json:"note"`
	Tools []record `json:"tools"`
}

const note = "GENERATED by cmd/toolgen — do not edit. The tools an assistant may call, " +
	"derived from internal/resource. Every tool is a list except change_row, which proposes " +
	"one row change through the same pipeline a human form uses; no RouterOS action verb is " +
	"advertised. internal/verify checks this against the live registry in both directions."

func main() {
	out := flag.String("out", outRel, "file to write")
	check := flag.Bool("check", false, "fail if the committed file is stale instead of writing it")
	flag.Parse()

	body, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, "toolgen:", err)
		os.Exit(1)
	}

	if *check {
		have, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "toolgen: %s is missing; run `go run ./cmd/toolgen`\n", *out)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(body)) {
			fmt.Fprintf(os.Stderr, "toolgen: %s is STALE — the tools an assistant may call "+
				"changed and the record was not regenerated.\nRun: go run ./cmd/toolgen\n", *out)
			os.Exit(1)
		}
		fmt.Printf("toolgen: %s is current (%d tools)\n", *out, len(aitools.All()))
		return
	}

	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "toolgen:", err)
		os.Exit(1)
	}
	fmt.Printf("toolgen: wrote %s — %d tools\n", *out, len(aitools.All()))
}

func render() ([]byte, error) {
	tools := aitools.All()
	if len(tools) < 10 {
		// A FLOOR, so a registry that stopped enumerating writes an empty record
		// rather than silently narrowing what the assistant can see to nothing.
		return nil, fmt.Errorf("only %d tools — the resource registry is not being read", len(tools))
	}
	rows := make([]record, 0, len(tools))
	for _, t := range tools {
		rows = append(rows, record{Name: t.Name, Access: t.Access, Resource: t.Resource, Page: t.Page})
	}
	b, err := json.MarshalIndent(artefact{Note: note, Tools: rows}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}
