package geo

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

// The corpus is generated by RUNNING `src/cityIndex.js` over geoip-lite's own
// data, so `hits` is the live module's answer — ranking included.
//
// A geoip-lite data refresh changes these answers. That is drift to regenerate,
// which `--check` reports; it is not a port defect, and NOTHING here asserts a
// record count, exactly as the live header forbids.
type cityCase struct {
	Q     string  `json:"q"`
	Limit any     `json:"limit"`
	Hits  []Place `json:"hits"`
}

func loadCityCases(t *testing.T) []cityCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "city-index-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/city-index-cases.js)", err)
	}
	var doc struct {
		Cases []cityCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) < 20 {
		t.Fatalf("the corpus holds %d queries — it is not the generated one", len(doc.Cases))
	}
	return doc.Cases
}

// limitArg renders the corpus's raw limit the way a query parameter would
// arrive. `null` means the caller passed none.
func limitArg(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case float64:
		if x == float64(int64(x)) {
			return strconv.FormatInt(int64(x), 10)
		}
		return strconv.FormatFloat(x, 'f', -1, 64)
	default:
		return ""
	}
}

func TestCitySearchMatchesTheLiveModule(t *testing.T) {
	dir := dataDir(t) // skips when geoip-lite data is absent
	idx, err := BuildCityIndex(dir)
	if err != nil {
		t.Fatalf("BuildCityIndex: %v", err)
	}

	for _, c := range loadCityCases(t) {
		name := c.Q + "/" + limitArg(c.Limit)
		t.Run(name, func(t *testing.T) {
			got := idx.Search(c.Q, limitArg(c.Limit))
			if len(got) != len(c.Hits) {
				t.Fatalf("got %d hits, live has %d", len(got), len(c.Hits))
			}
			for i := range got {
				a, _ := json.Marshal(got[i])
				b, _ := json.Marshal(c.Hits[i])
				if string(a) != string(b) {
					t.Errorf("hit %d\n  got  %s\n  live %s", i, a, b)
				}
			}
		})
	}
}

// THE LIMIT RULES, which read as though 0 and -3 behave alike and do not.
//
// `parseInt(0) || 20` is 20 because zero is FALSY, so asking for none returns the
// default; a negative parses truthy and is clamped up to 1. Pinned here as well
// as in the corpus because the expression invites exactly the wrong reading.
func TestLimitClamping(t *testing.T) {
	cases := []struct {
		raw  string
		want int
	}{
		{"", 20}, {"0", 20}, {"abc", 20},
		{"-3", 1}, {"1", 1}, {"7", 7},
		{"20.9", 20}, {"999", 50}, {"50", 50}, {"51", 50},
	}
	for _, c := range cases {
		if got := clampLimit(c.raw); got != c.want {
			t.Errorf("clampLimit(%q) = %d, want %d", c.raw, got, c.want)
		}
	}
}

// A one-letter query is refused before the index is even consulted — it matches
// thousands of places and is never a real intent.
func TestShortQueriesAreRefused(t *testing.T) {
	idx := &CityIndex{}
	for _, q := range []string{"", " ", "a", " a "} {
		if got := idx.Search(q, ""); len(got) != 0 {
			t.Errorf("Search(%q) returned %d hits", q, len(got))
		}
	}
}
