package collection

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The corpus is generated by RUNNING `src/collection.js`, so `want` is the live
// module's own answer rather than anything typed here.
type resolveCase struct {
	Name     string         `json:"name"`
	Settings map[string]any `json:"settings"`
	Record   *struct {
		DefaultIf  any `json:"defaultIf"`
		PingTarget any `json:"pingTarget"`
		Collection *struct {
			Mode      string `json:"mode"`
			Off       any    `json:"off"`
			Overrides any    `json:"overrides"`
		} `json:"collection"`
	} `json:"record"`
	Fingerprint string `json:"fingerprint"`
	Want        struct {
		Mode      string          `json:"mode"`
		Poll      map[string]int  `json:"poll"`
		Stream    map[string]bool `json:"stream"`
		Enabled   map[string]bool `json:"enabled"`
		Overrides map[string]any  `json:"overrides"`
	} `json:"want"`
}

func loadCases(t *testing.T) []resolveCase {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "collection-cases.json"))
	if err != nil {
		t.Fatalf("corpus: %v (regenerate with tools/collection-cases.js)", err)
	}
	var doc struct {
		Cases []resolveCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Cases) < 20 {
		t.Fatalf("corpus holds %d cases — it is not the generated one", len(doc.Cases))
	}
	return doc.Cases
}

// routerFor rebuilds the Router the case was given.
//
// `overrides` arrives as `any` on purpose: the corpus carries a case where it is
// a STRING, because a hand-edited routers.json can hold one and the resolver
// ignores it. Decoding it into a typed field would make that case
// unrepresentable. The cases' `off` lists are deliberately NOT read: a stored off
// list is ignored since per-router switching was removed, and the cases that
// carry one now prove exactly that (see also TestAStoredOffListIsIgnored).
func routerFor(c resolveCase) *Router {
	if c.Record == nil || c.Record.Collection == nil {
		return nil
	}
	cc := c.Record.Collection
	r := &Router{Mode: cc.Mode}
	if m, ok := cc.Overrides.(map[string]any); ok {
		r.Overrides = m
	}
	return r
}

// goOnlyCollectors are in this registry and were never in the live Node module,
// so no recorded corpus can carry them.
//
// ── A LEDGER, NOT AN EXEMPTION LIST ─────────────────────────────────────────
//
// The corpus is a RECORDING of what the live module resolved. A collector the
// live app never had cannot appear in it, and pretending otherwise would mean
// hand-editing a recording — which is how a corpus stops being evidence.
//
// So the divergence is named here and checked BOTH ways: an extra key that is
// not named is a real drift, and a named key that Resolve does not produce is an
// entry to delete. `areas` is the first: one collector for every generated page,
// declared in internal/areas, with no live counterpart at all.
var goOnlyCollectors = map[string]bool{"areas": true}

func TestResolveMatchesTheLiveModule(t *testing.T) {
	for _, c := range loadCases(t) {
		t.Run(c.Name, func(t *testing.T) {
			got := Resolve(c.Settings, routerFor(c))

			if got.Mode != c.Want.Mode {
				t.Errorf("mode = %q, live says %q", got.Mode, c.Want.Mode)
			}
			for k, want := range c.Want.Poll {
				if got.Poll[k] != want {
					t.Errorf("poll[%s] = %d, live says %d", k, got.Poll[k], want)
				}
			}
			extra := 0
			for k := range got.Poll {
				if _, recorded := c.Want.Poll[k]; recorded {
					continue
				}
				extra++
				if !goOnlyCollectors[k] {
					t.Errorf("poll has %q, which the live module never resolved and which is "+
						"not recorded as Go-only", k)
				}
			}
			if len(got.Poll)-extra != len(c.Want.Poll) {
				t.Errorf("poll has %d keys (%d of them Go-only), live has %d",
					len(got.Poll), extra, len(c.Want.Poll))
			}
			for k, want := range c.Want.Stream {
				if got.Stream[k] != want {
					t.Errorf("stream[%s] = %v, live says %v", k, got.Stream[k], want)
				}
			}
			for k, want := range c.Want.Enabled {
				if got.Enabled[k] != want {
					t.Errorf("enabled[%s] = %v, live says %v", k, got.Enabled[k], want)
				}
			}
		})
	}
}

// The EMBEDDED registry must match the one the corpus was generated from. They
// come from the same generator run, so this catches an asset edited by hand and
// a half-applied regeneration — not a live-side change, which `--check` catches.
func TestTheEmbeddedRegistryMatchesTheCorpus(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "..", "testdata", "collection-cases.json"))
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Cases []resolveCase `json:"cases"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	// Every collector the corpus resolved must exist in the embedded registry,
	// and vice versa — a row dropped from either side is the failure here.
	want := map[string]bool{}
	for k := range doc.Cases[0].Want.Enabled {
		want[k] = true
	}
	got := map[string]bool{}
	for _, c := range Collectors() {
		got[c.Key] = true
	}
	for k := range want {
		if !got[k] {
			t.Errorf("the corpus resolved %q, which the embedded registry does not hold", k)
		}
	}
	for k := range got {
		if !want[k] && !goOnlyCollectors[k] {
			t.Errorf("the embedded registry holds %q, which the corpus never resolved", k)
		}
	}
	// AND THE OTHER DIRECTION: a Go-only collector that has been removed, or
	// that the live corpus has caught up with, leaves an entry claiming a
	// divergence that no longer exists.
	for k := range goOnlyCollectors {
		if !got[k] {
			t.Errorf("%q is recorded as Go-only but the registry no longer holds it", k)
		}
		if want[k] {
			t.Errorf("%q is recorded as Go-only but the corpus resolved it — delete the entry", k)
		}
	}
}

// The registry must keep the SHAPE the resolver depends on. A table that arrived
// with every `pollable` false would make every collector a stream and still
// satisfy the corpus if the corpus were regenerated from it.
func TestTheRegistryStillDiscriminates(t *testing.T) {
	var pollable, streamKeyed, disableable int
	for _, c := range Collectors() {
		if c.Pollable {
			pollable++
		}
		if c.StreamKey != "" {
			streamKeyed++
		}
		if c.Disableable {
			disableable++
		}
	}
	if pollable == 0 || pollable == len(Collectors()) {
		t.Errorf("%d of %d collectors are pollable — the non-pollable branch is unreachable",
			pollable, len(Collectors()))
	}
	if streamKeyed == 0 {
		t.Error("no collector has a streamKey — the override branch is unreachable")
	}
	if disableable == 0 {
		t.Error("no collector is disableable — dormancy can suspend nothing")
	}
}

// withoutGoOnly removes the Go-only collectors' entries from a fingerprint, so
// what is compared with the recording is the part the recording could know about.
func withoutGoOnly(fp string) string {
	for key := range goOnlyCollectors {
		// The poll value comes from the REGISTRY, not from a literal here: a
		// default changed there and not here would leave the entry in and fail
		// with a diff nobody can read.
		forms := []string{key + "=false,", key + "=true,"}
		for _, c := range Collectors() {
			if c.Key == key {
				forms = append(forms, key+"="+strconv.Itoa(c.DefaultPollMs)+",")
			}
		}
		for _, form := range forms {
			fp = strings.ReplaceAll(fp, form, "")
		}
		// A value this helper does not know about must not pass silently.
		if strings.Contains(fp, key+"=") {
			panic("a Go-only collector's fingerprint entry was not removed: " + key)
		}
	}
	return fp
}

func TestFingerprintMatchesTheLiveModule(t *testing.T) {
	seen := map[string]string{}
	for _, c := range loadCases(t) {
		t.Run(c.Name, func(t *testing.T) {
			var extras RecordExtras
			if c.Record != nil {
				extras = RecordExtras{DefaultIf: c.Record.DefaultIf, PingTarget: c.Record.PingTarget}
			}
			// WITHOUT THE GO-ONLY COLLECTORS, and only those: the fingerprint
			// names every collector, so one the live module never had shifts the
			// whole string. Dropping exactly the recorded names keeps every live
			// key compared, and `goOnlyCollectors` is held both ways above.
			got := withoutGoOnly(Fingerprint(c.Settings, routerFor(c), extras))
			if got != c.Fingerprint {
				t.Errorf("fingerprint\n  got  %s\n  live %s", got, c.Fingerprint)
			}
		})
		seen[c.Name] = c.Fingerprint
	}

	// THE POINT OF THE FINGERPRINT, asserted rather than assumed: two inputs that
	// RESOLVE identically must still differ here when a field outside
	// `collection` differs, or a router edit would skip a rebuild it needs.
	if seen["settings topN"] == seen["defaults: no settings, no record"] {
		t.Error("a settings key outside `collection` did not change the fingerprint")
	}
	// And the coercion asymmetry between the two groups: a RECORD extra of 0 is
	// indistinguishable from empty, a SETTINGS extra of 0 is not.
	if seen["a record extra that is ZERO"] != seen["a record extra that is EMPTY"] {
		t.Error("a record extra of 0 and of \"\" fingerprinted differently")
	}
	if seen["a settings extra that is ZERO"] == seen["defaults: no settings, no record"] {
		t.Error("a settings extra of 0 fingerprinted as absent")
	}
}

// TestAStoredOffListIsIgnored — per-router collector switching was removed on
// 2026-09-15. A routers.json written before then may still carry `off`, and it
// must switch nothing off, through the old dependency cascade included, while the
// rest of the block still counts.
func TestAStoredOffListIsIgnored(t *testing.T) {
	got := Resolve(map[string]any{}, ParseRouter([]byte(`{"mode":"poll","off":["wifi","conns"]}`)))
	for _, c := range Collectors() {
		if !got.Enabled[c.Key] {
			t.Errorf("%s resolved as disabled from a stored off list", c.Key)
		}
	}
	if got.Mode != "poll" {
		t.Errorf("the rest of the block was lost with the off list: mode = %q", got.Mode)
	}
	// ── NOTHING DISABLES A COLLECTOR ANY MORE ──────────────────────────────
	//
	// This checked that the install-wide ping switch turned ping off. That
	// switch was removed on 2026-09-17, so the check is replaced by the
	// invariant it became rather than dropped: no input leaves any collector
	// disabled. The uniformity is what lets every consumer stop asking whether
	// a collector is on before using what it holds.
	for _, in := range []map[string]any{
		{},
		{"pingEnabled": false},
		{"pingEnabled": "false"},
		{"pingEnabled": false, "rosDebug": true},
	} {
		got := Resolve(in, nil).Enabled
		if len(got) < 10 {
			t.Fatalf("settings %v resolved only %d collectors; the registry is not being read",
				in, len(got))
		}
		for key, on := range got {
			if !on {
				t.Errorf("settings %v left %q disabled; no collector can be switched off", in, key)
			}
		}
	}
}
