'use strict';
/**
 * The alerter's PURE helpers, as a corpus generated by RUNNING
 * `src/alerter.js`.
 *
 * The evaluator, the cooldown maps and the delivery are not ported: they hold
 * per-router state and they send. What is here is the four functions that decide
 * how an alert READS — the template renderer, the interface classifier, its
 * settings-key map, and the label a stored alert type is shown under.
 *
 * `labelFor` is exported; the other three are module-private and are LIFTED by
 * source. Requiring the module is impossible on the host anyway — it reaches
 * `db.js`, and `better-sqlite3` is a native module that is not installed here.
 *
 * ---- THE TRAPS THE CASES ARE SHAPED AROUND ---------------------------------
 *
 *   `_render`      `{{x}}` where `x` is UNDEFINED becomes empty — but where it
 *                  is NULL becomes the text "null", because the guard tests
 *                  `=== undefined` only. Control characters are stripped and the
 *                  result capped at 200, IN THAT ORDER.
 *   `_ifaceType`   an explicit type wins, and `wifi` normalises to `wlan` — but
 *                  the string "unknown" FALLS THROUGH to name detection, as does
 *                  an empty one, while any other unrecognised type is "other".
 *                  A name ending `.10` is a vlan.
 *   `labelFor`     acronyms are per WORD, so `cpu_ok` is "CPU OK" and not
 *                  "Cpu Ok" — and an unmapped type still reads as words rather
 *                  than leaking a database column.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/alerter-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/alerter-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const src = fs.readFileSync(path.join(LIVE, 'src', 'alerter.js'), 'utf8');

function slice(startsWith) {
  const i = src.indexOf(startsWith);
  assert.ok(i > 0, 'cannot find ' + startsWith.trim());
  const j = src.indexOf('\n}', i);
  assert.ok(j > i && j - i < 1400, startsWith.trim() + ' is not where its anchors say');
  return src.slice(i, j + 2);
}
function constBlock(name) {
  const i = src.indexOf('const ' + name);
  assert.ok(i > 0, 'cannot find ' + name);
  const j = src.indexOf('};', i);
  return src.slice(i, j + 2);
}

const parts = [
  slice('function _render(tpl, vars) {'),
  slice('function _ifaceType(name, type) {'),
  slice('function _ifaceTypeKey(type) {'),
  constBlock('ALERT_LABELS'),
  constBlock('_LABEL_ACRONYMS'),
  slice('function labelFor(alertType) {'),
];
assert.ok(parts[0].includes('x00-\\x1f'), 'the lifted _render lost its control-character strip');
assert.ok(parts[1].includes("'wifi'"), 'the lifted _ifaceType lost the wifi normalisation');
assert.ok(parts[5].includes('_LABEL_ACRONYMS'), 'the lifted labelFor lost its acronym table');

const ctx = { String, Object };
vm.createContext(ctx);
vm.runInContext(parts.join('\n') +
  '\nglobalThis.__r = _render; globalThis.__t = _ifaceType;' +
  '\nglobalThis.__k = _ifaceTypeKey; globalThis.__l = labelFor;', ctx);
const render = ctx.__r, ifaceType = ctx.__t, ifaceKey = ctx.__k, labelFor = ctx.__l;

const RENDERS = [
  ['a plain substitution', '{{a}}', { a: 'x' }],
  ['two of them', '{{a}}-{{b}}', { a: '1', b: '2' }],
  ['a repeated key', '{{a}}{{a}}', { a: 'z' }],
  ['no placeholders', 'plain text', { a: 'x' }],
  ['a missing key', '{{nope}}', {}],
  // `=== undefined` is the ONLY guard, so null renders as the word.
  ['an explicit undefined', '{{a}}', { a: undefined }],
  ['an explicit null', '{{a}}', { a: null }],
  ['a number', '{{a}}', { a: 42 }],
  ['a boolean', '{{a}}', { a: false }],
  ['zero', '{{a}}', { a: 0 }],
  ['an empty string', '{{a}}', { a: '' }],
  // Control characters are stripped, then the result is cut at 200.
  ['a newline in a value', '{{a}}', { a: 'one\ntwo' }],
  ['a NUL and a DEL', '{{a}}', { a: 'a\x00b\x7fc' }],
  ['a tab', '{{a}}', { a: 'a\tb' }],
  ['a long value', '{{a}}', { a: 'x'.repeat(400) }],
  ['a long value full of control characters', '{{a}}', { a: ('x\n').repeat(300) }],
  ['a value that looks like a placeholder', '{{a}}', { a: '{{b}}' }],
  ['a malformed placeholder', '{{ a }}', { a: 'x' }],
  ['a non-word key', '{{a-b}}', { 'a-b': 'x' }],
];

const IFACES = [
  ['ether by type', 'anything', 'ether'],
  ['wlan by type', 'anything', 'wlan'],
  ['wifi normalises to wlan', 'anything', 'wifi'],
  ['WIFI uppercase', 'anything', 'WIFI'],
  ['bridge by type', 'anything', 'bridge'],
  ['vlan by type', 'anything', 'vlan'],
  ['an unrecognised type is other', 'ether1', 'pppoe'],
  // "unknown" and "" FALL THROUGH to the name.
  ['type unknown falls through', 'ether1', 'unknown'],
  ['type empty falls through', 'wlan1', ''],
  ['type missing falls through', 'bridge-lan', undefined],
  ['name ether', 'ether5', undefined],
  ['name wlan', 'wlan1', undefined],
  ['name wireless', 'wireless2', undefined],
  ['name wifi', 'wifi1', undefined],
  ['name bridge', 'bridge1', undefined],
  ['name vlan', 'vlan10', undefined],
  // THE NAME CHECKS ARE ORDERED. `ether1.10` is an ETHER, not a vlan, because
  // `/^ether/` is tested before the dotted-suffix pattern — so the vlan rule
  // only ever sees names that start with none of the earlier prefixes.
  ['a dotted name that starts with ether', 'ether1.10', undefined],
  ['a dotted name that reaches the vlan rule', 'sfp1.20', undefined],
  ['an unmatched name', 'sfp-sfpplus1', undefined],
  ['an empty name', '', undefined],
];

const LABELS = [
  'routeros_update', 'routeros_updated', 'connectivity',
  'cpu', 'cpu_ok', 'bgp_down', 'vpn_up', 'os_mismatch',
  'disk_full', 'some_new_alert', 'ALREADY_UPPER', '', null, 'single',
];

const cases = {
  renders: RENDERS.map(([name, tpl, vars]) => ({ name, tpl, vars, want: render(tpl, vars) })),
  ifaces: IFACES.map(([name, iface, type]) => ({
    name, iface, type: type === undefined ? null : type,
    want: ifaceType(iface, type), key: ifaceKey(ifaceType(iface, type)),
  })),
  labels: LABELS.map((t) => ({ type: t, want: labelFor(t) })),
};

// ---- BELIEVABILITY --------------------------------------------------------
{
  const r = (n) => cases.renders.find((c) => c.name === n).want;
  assert.equal(r('an explicit undefined'), '', 'undefined did not render empty');
  assert.equal(r('an explicit null'), 'null',
    'null rendered empty — then nothing here distinguishes the `=== undefined` guard from a ' +
    'looser one, which is the difference between an empty field and the word "null" in an alert');
  assert.equal(r('a newline in a value'), 'onetwo', 'the control-character strip did not run');
  assert.ok(r('a long value').length === 200, 'the 200-character cap did not apply');
  assert.equal(r('zero'), '0', 'zero rendered as empty');

  const t = (n) => cases.ifaces.find((c) => c.name === n).want;
  assert.equal(t('wifi normalises to wlan'), 'wlan', 'wifi did not normalise');
  assert.equal(t('type unknown falls through'), 'ether', '"unknown" did not fall through to the name');
  assert.equal(t('an unrecognised type is other'), 'other', 'an unrecognised type was not "other"');
  assert.equal(t('a dotted name that starts with ether'), 'ether',
    'the name checks are not ordered: `ether1.10` must be an ether, since /^ether/ is tested first');
  assert.equal(t('a dotted name that reaches the vlan rule'), 'vlan',
    'a dotted name that starts with no known prefix must be a vlan');
  assert.ok(new Set(cases.ifaces.map((c) => c.want)).size >= 4, 'the interface corpus is not discriminating');

  const l = (ty) => cases.labels.find((c) => c.type === ty).want;
  assert.equal(l('routeros_update'), 'Update Available', 'the mapped label is wrong');
  assert.equal(l('cpu_ok'), 'CPU OK', 'the acronyms are not applied per word');
  assert.equal(l('some_new_alert'), 'Some New Alert', 'an unmapped type did not read as words');
  assert.equal(l(''), 'Alert', 'an empty type did not fall back');
}

const FILE = path.join(ROOT, 'testdata', 'alerter-cases.json');
const text = JSON.stringify(cases, null, 2) + '\n';
if (process.argv.includes('--check')) {
  const have = fs.existsSync(FILE) ? fs.readFileSync(FILE, 'utf8') : '';
  if (have !== text) {
    console.error('alerter-cases: STALE — regenerate with `node tools/alerter-cases.js`');
    process.exit(1);
  }
  console.log('alerter-cases: ' + cases.renders.length + ' renders, ' + cases.ifaces.length +
    ' interfaces, ' + cases.labels.length + ' labels current');
} else {
  fs.writeFileSync(FILE, text);
  console.log('alerter-cases: wrote ' + cases.renders.length + ' renders, ' +
    cases.ifaces.length + ' interfaces and ' + cases.labels.length + ' labels');
}
