'use strict';
/**
 * ASN table — the curated IP-range → org list, lifted into Go.
 *
 * ── WHY THIS IS GENERATED AND NOT TYPED ─────────────────────────────────────
 *
 * `src/util/asnLookup.js` carries roughly 280 lines of CIDR literals sourced
 * from Cloudflare's, Google's, AWS's and half a dozen other publications. Typing
 * them into Go by hand is the same class of mistake as retyping markup: one
 * transposed digit gives a range that silently matches the wrong traffic, and
 * nothing about the result looks wrong. `104.16.0.0/13` and `104.16.0.0/18`
 * differ by one character and by two million addresses.
 *
 * So the table is EXTRACTED, exactly as tools/extract-ui.js extracts the page
 * bodies, and `--check` fails when the live list moves. Transcription errors
 * become impossible rather than unlikely, and drift is caught rather than
 * discovered.
 *
 * ── ORDER IS PART OF THE DATA ───────────────────────────────────────────────
 *
 * The original stops at the FIRST matching entry — "more specific entries should
 * come before broader ones", says its header — so entry order is preserved
 * verbatim. Within one entry the order does not matter and is not relied on:
 * every range there yields the same org, so the ranges are split into v4 and v6
 * lists, which is how the Go side can skip a whole family in one test.
 *
 *   node tools/asn-table.js            write internal/asn/table.go
 *   node tools/asn-table.js --check    exit 1 if stale
 */

const fs = require('node:fs');
const path = require('node:path');

const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(__dirname, '..', '..', 'MikroDash'));
const SRC = path.join(LIVE, 'src', 'util', 'asnLookup.js');
const OUT = path.join(__dirname, '..', 'internal', 'asn', 'table.go');

/**
 * Lift an array or object literal out of the source by name.
 *
 * The module exports only its two functions, so `require` cannot reach the
 * tables — they have to come out of the text. A brace counter rather than a
 * regex: the literal spans 250 lines and carries both kinds of comment.
 */
function liftLiteral(src, name, open, close) {
  const start = src.indexOf('const ' + name + ' = ' + open);
  if (start === -1) throw new Error(name + ' not found in ' + SRC);
  const from = src.indexOf(open, start);
  let depth = 0;
  let i = from;
  for (; i < src.length; i++) {
    if (src[i] === open) depth++;
    else if (src[i] === close) {
      depth--;
      if (depth === 0) break;
    }
  }
  if (depth !== 0) throw new Error(name + ' is not balanced');
  // The literal is pure data — strings, arrays and objects — so evaluating it is
  // reading it. Nothing else in that file is touched.
  //
  // ON `new Function`: the input is the LIVE REPO'S OWN SOURCE, which this
  // project already trusts enough to `require()` from a dozen tools, and this
  // runs at generation time on a developer's machine rather than in the server.
  // The alternative — JSON.parse — cannot read it: the literal carries comments,
  // trailing commas and single-quoted strings. Nothing here ever sees a value
  // from a router, a fixture or a request.
  return new Function('return ' + src.slice(from, i + 1))();
}

function goStr(s) {
  return JSON.stringify(String(s));
}

function main() {
  const check = process.argv.includes('--check');
  const src = fs.readFileSync(SRC, 'utf8');
  const orgs = liftLiteral(src, 'ORGS', '[', ']');
  const cats = liftLiteral(src, 'ORG_CATEGORY', '{', '}');

  let v4Count = 0, v6Count = 0;
  const entries = orgs.map((e) => {
    // A colon is how the original tells the families apart, and using the same
    // test means a malformed entry lands in the same list on both sides.
    const v4 = e.ranges.filter((r) => !r.includes(':'));
    const v6 = e.ranges.filter((r) => r.includes(':'));
    v4Count += v4.length;
    v6Count += v6.length;
    return { org: e.org, v4, v6 };
  });

  const lines = [];
  lines.push('package asn');
  lines.push('');
  lines.push('// Code generated by tools/asn-table.js from src/util/asnLookup.js. DO NOT EDIT.');
  lines.push('//');
  lines.push('// Regenerate with:  node tools/asn-table.js');
  lines.push('// Verify with:      node tools/asn-table.js --check');
  lines.push('//');
  lines.push('// ENTRY ORDER IS LOAD-BEARING: the lookup stops at the first match, and the');
  lines.push('// original orders specific entries before broad ones. Range order within an');
  lines.push('// entry is not — every range there yields the same org.');
  lines.push('');
  lines.push('var orgs = []entry{');
  for (const e of entries) {
    lines.push('\t{org: ' + goStr(e.org) + ',');
    lines.push('\t\tv4: []string{' + e.v4.map(goStr).join(', ') + '},');
    lines.push('\t\tv6: []string{' + e.v6.map(goStr).join(', ') + '},');
    lines.push('\t},');
  }
  lines.push('}');
  lines.push('');
  lines.push('// categories maps an org to its colour class. Anything unmapped is "other",');
  lines.push('// which the lookup supplies rather than this table.');
  lines.push('var categories = map[string]string{');
  // ALIGNED THE WAY gofmt ALIGNS IT. A generator whose output fails the repo's
  // own `gofmt -l` check is a trap: the first person to run gofmt makes the file
  // differ from what the generator emits, and `--check` then reports the table
  // as stale when nothing upstream moved. Emitting the column here means the two
  // agree by construction.
  const keys = Object.keys(cats);
  const width = Math.max(...keys.map((k) => goStr(k).length + 1));
  for (const org of keys) {
    const key = goStr(org) + ':';
    lines.push('\t' + key + ' '.repeat(width - key.length + 1) + goStr(cats[org]) + ',');
  }
  lines.push('}');
  const body = lines.join('\n') + '\n';

  if (check) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (cur !== body) {
      console.error('internal/asn/table.go is stale — asnLookup.js has changed.\n' +
                    'Run: node tools/asn-table.js');
      process.exit(1);
    }
    console.log('asn table up to date (' + entries.length + ' orgs, ' +
                v4Count + ' v4 ranges, ' + v6Count + ' v6)');
    return;
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log('wrote ' + path.relative(path.join(__dirname, '..'), OUT) +
    ' — ' + entries.length + ' orgs, ' + v4Count + ' v4 ranges, ' + v6Count + ' v6, ' +
    Object.keys(cats).length + ' categories');
}

main();
