'use strict';
/**
 * Bandwidth cases — what the LIVE collector makes of the captured connection
 * table, for the Go port to reproduce.
 *
 * WHY A GENERATOR AND NOT A FIXTURE. `src/collectors/bandwidth.js` performs no
 * router I/O at all: it reads the snapshot the CONNECTIONS collector deposits in
 * `connTableCache` and transforms it. A capture run against real hardware
 * reported "tick() + start() produced neither a read nor a stream row", which is
 * the honest answer rather than a gap — there is nothing to capture.
 *
 * So the input comes from the `conns` fixture, which holds one read of 431 rows
 * with exactly the proplist this transform needs.
 *
 * TWO SNAPSHOTS, THE SECOND SYNTHESISED. The whole collector is byte-counter
 * DELTAS between ticks, so one snapshot produces no rates at all. The second is
 * built from the first by advancing the counters on a fixed rule, which makes
 * the rates synthetic and the join, the aggregation, the top-destination pick
 * and the sort fully exercised — on inputs both implementations see byte for
 * byte.
 *
 * GEO AND ASN ARE OFF. They read a MaxMind database that is not part of the
 * port, and a golden that varied with a downloaded database would not be a gate.
 * `country`, `city`, `org` and `cat` are therefore empty here by construction,
 * and the Go side is asked for the same.
 *
 *   node tools/bandwidth-cases.js            write testdata/bandwidth-cases.json
 *   node tools/bandwidth-cases.js --check    exit 1 if stale
 */

const fs = require('node:fs');
const path = require('node:path');

const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(__dirname, '..', '..', 'MikroDash'));
const OUT = path.join(__dirname, '..', 'testdata', 'bandwidth-cases.json');
const FIXTURE = path.join(__dirname, '..', 'testdata', 'fixtures',
  'Mikrotik identity-0cc5 AX3', 'conns.json');

const BandwidthCollector = require(path.join(LIVE, 'src', 'collectors', 'bandwidth.js'));

/**
 * The counter advance, as a pure function of the row's position.
 *
 * Deterministic and spread across three orders of magnitude, so the sort has
 * something to sort and the top-destination pick has a real winner. A constant
 * bump would make every device identical and the gate would pass on an
 * implementation that ignored the numbers entirely.
 */
function advance(row, i) {
  const orig = parseInt(row['orig-bytes'] || '0', 10) || 0;
  const repl = parseInt(row['repl-bytes'] || '0', 10) || 0;
  return {
    ...row,
    'orig-bytes': String(orig + (i % 7) * 1500 + (i % 3) * 40000),
    'repl-bytes': String(repl + (i % 5) * 9000 + (i % 11) * 700),
  };
}

/** The two things the collector reads from the outside world, stubbed. */
function harness(rows, snapshotTs) {
  return {
    ros: { connected: true, routerLabel: 'cases', on() {} },
    io: {
      engine: { clientsCount: 1 },
      to() { return this; },
      emit() {},
    },
    state: {},
    pollMs: 3000,
    // The LAN ranges. Passed explicitly rather than left to the RFC-1918
    // fallback so the case set states what it filters on.
    dhcpNetworks: { getLanCidrs: () => ['198.51.100.0/24'] },
    // No lease or ARP source: every device comes back unnamed, which is what a
    // router that is not its clients' DHCP server also produces.
    dhcpLeases: null,
    arp: null,
    ifStatus: null,
    geoLookup: null,
    geoOrgCache: { geo: new Map(), org: new Map() },
    connTableCache: { latestWithTs: () => ({ rows, ts: snapshotTs }) },
  };
}

async function main() {
  const check = process.argv.includes('--check');
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'));
  const rows = (fixture.exchanges || []).flatMap((e) => e.rows || []);
  if (!rows.length) throw new Error('the conns fixture holds no rows');

  // Fixed timestamps: the rates are bytes per elapsed millisecond, so a
  // wall-clock reading here would make the output differ on every run.
  const T0 = 1_000_000_000_000;
  const DT = 5000;

  const first = harness(rows, T0);
  const c = new BandwidthCollector(first);
  await c.tick(true);
  const firstPayload = c.lastPayload;

  // The second snapshot, same collector instance — the deltas live in `_prev`.
  const moved = rows.map(advance);
  c.connTableCache = { latestWithTs: () => ({ rows: moved, ts: T0 + DT }) };
  await c.tick(true);
  const secondPayload = c.lastPayload;

  const cases = {
    note: 'Generated by tools/bandwidth-cases.js — do not edit. See its header for why ' +
          'this collector has a generator rather than a fixture.',
    lanCidrs: ['198.51.100.0/24'],
    t0: T0, dt: DT,
    rows: rows.length,
    // The FIRST tick has no baseline, so every rate is zero and the device list
    // is whatever the LAN filter admits. Pinned deliberately: a port that
    // invented rates from one reading would pass a gate that only checked the
    // second.
    first: firstPayload ? { devices: firstPayload.devices } : null,
    second: secondPayload ? { devices: secondPayload.devices } : null,
  };

  const body = JSON.stringify(cases, null, 2) + '\n';
  if (check) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (cur !== body) {
      console.error('testdata/bandwidth-cases.json is stale — run: node tools/bandwidth-cases.js');
      process.exit(1);
    }
    console.log('bandwidth cases up to date (' + (cases.second?.devices.length || 0) + ' devices)');
    return;
  }
  fs.writeFileSync(OUT, body);
  console.log('wrote ' + path.relative(path.join(__dirname, '..'), OUT) +
    ' — ' + rows.length + ' rows in, ' +
    (cases.first?.devices.length || 0) + ' devices on the first tick, ' +
    (cases.second?.devices.length || 0) + ' on the second');
}

main().catch((e) => { console.error(e); process.exit(1); });
