'use strict';
/**
 * The PER-ROUTER COLLECTION CONFIG (#105), as a corpus generated by RUNNING the
 * live `src/collection.js`.
 *
 * `resolveCollection(settings, routerRecord)` decides, for one router: every
 * collector's poll interval, whether it streams or polls, and whether it runs at
 * all. The port has NONE of it — `session.Session` and `routers.Pool` both pass
 * `0` for every interval and construct every collector — so a fleet where one
 * router has WiFi turned off is served identically to one where it is on, and a
 * hAP ac2 acting as an access point is asked for the same channels as a hAP ax3.
 * That is the problem #105 was filed about.
 *
 * ---- TWO ARTEFACTS, BECAUSE THERE ARE TWO WAYS TO GET THIS WRONG -----------
 *
 * 1. THE REGISTRY. Everything derives from `COLLECTORS` — the modal's
 *    checkboxes, the null-collector stub, the dormancy list, the tests. It is
 *    ~180 lines of data, and a Go copy typed by hand is a transcription error
 *    waiting to happen: one wrong `pollable` and a collector silently loses its
 *    poll path. Emitted here as JSON so the Go side's own table can be checked
 *    against it field for field.
 *
 * 2. THE RESOLUTION. A matrix of settings × router records through the live
 *    function, so precedence, clamping, the mode rules and the DEPENDENCY
 *    CASCADE are pinned by what the original actually does.
 *
 * ---- WHAT THE MATRIX IS SHAPED AROUND --------------------------------------
 *
 * Each case exists for a specific way the port could be wrong:
 *
 *   an override beats the global, which beats the collector's own default
 *   a stream override accepts the BOOLEAN true and the STRING 'true'
 *   `mode: 'poll'` changes delivery and must NOT change any interval
 *   an unknown mode falls back to 'stream' rather than being honoured
 *   a non-pollable collector (logs, traffic) is ALWAYS a stream
 *   a collector with no streamKey (bandwidth) is NEVER one
 *   `pingEnabled: false` is a global kill switch applied AFTER the per-router off list
 *   `pollIfaces` is interfaceStatus's METADATA interval with its own 60000 default
 *   turning off a collector others depend on CASCADES (`bandwidth` needs `conns`)
 *
 * ---- ONE THING THIS CORPUS CANNOT REACH, MEASURED RATHER THAN ASSUMED ------
 *
 * The live cascade is a FIXPOINT LOOP ("loop until stable so a chain would also
 * settle"). Today's registry has exactly one dependency edge — `bandwidth`
 * requires `conns` — so the graph is one level deep and a single pass produces
 * the same answer. A Go port that used `for` once instead of looping would pass
 * every case here.
 *
 * That is recorded rather than papered over with a synthetic registry: the
 * corpus is generated from the REAL one, and inventing a deeper graph to test a
 * loop would be testing a fixture. The Go side keeps the loop because the
 * original has it and a second edge is a one-line registry change away.
 *   a garbage interval clamps or falls back rather than reaching a collector
 *
 *   MIKRODASH_SRC=../MikroDash node tools/collection-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/collection-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const mod = require(path.join(LIVE, 'src', 'collection.js'));
const { resolveCollection, COLLECTORS, collectionFingerprint } = mod;
assert.ok(typeof resolveCollection === 'function', 'collection.js no longer exports resolveCollection');
assert.ok(Array.isArray(COLLECTORS) && COLLECTORS.length > 10,
  'collection.js no longer exports the COLLECTORS registry');

/** The registry, reduced to the fields a resolver consumes. */
const registry = COLLECTORS.map((c) => ({
  key: c.key,
  // `label` is not used by the resolver. It is here because `GET /api/collectors`
  // sends it — `index.js` serves that route straight off this registry under the
  // alias `_COLLECTOR_DEFS` — and a Go server answering that route needs the same
  // words, not a second set typed here.
  label: c.label,
  pollKey: c.pollKey || null,
  defaultPollMs: c.defaultPollMs,
  streamKey: c.streamKey || null,
  pollable: !!c.pollable,
  disableable: !!c.disableable,
  requires: (c.requires || []).slice(),
  // ── ADDED 2026-08-28, FOR THE DORMANCY SUPERVISOR ────────────────────────
  //
  // `emptyKey` names the payload list(s) whose emptiness means "nothing to
  // report here", and it is what makes a collector ELIGIBLE for dormancy:
  // `_DORMANCY_DEFS = _COLLECTOR_DEFS.filter(c => c.emptyKey && c.disableable)`.
  // Without it the Go side cannot derive that list and would have to carry a
  // second, hand-typed one — which is the transcription error this whole file
  // exists to avoid.
  //
  // NORMALISED TO AN ARRAY, because the live value is a string for some
  // collectors and an array for others and `payloadEmpty` immediately does
  // `Array.isArray(emptyKey) ? emptyKey : [emptyKey]`. The shape is ASSERTED
  // below rather than coerced blindly: a third form must fail here, not arrive
  // in Go as an empty list that quietly makes a collector ineligible.
  emptyKey: c.emptyKey == null ? [] : (Array.isArray(c.emptyKey) ? c.emptyKey.slice() : [c.emptyKey]),
  // `sessionProp` is how the supervisor finds the collector on the session
  // object. Recorded for the same reason as `label`: the Go side needs the same
  // names, not a second set typed here.
  sessionProp: c.sessionProp || null,
}));

// THE SHAPE OF `emptyKey`, asserted rather than assumed. A value that is neither
// a string nor an array of strings would be normalised into nonsense above.
for (const c of COLLECTORS) {
  if (c.emptyKey == null) continue;
  const list = Array.isArray(c.emptyKey) ? c.emptyKey : [c.emptyKey];
  for (const k of list) {
    if (typeof k !== 'string' || !k) {
      throw new Error(`${c.key}: emptyKey holds ${JSON.stringify(k)}, which is neither a string `
        + 'nor an array of them — the normalisation above would silently drop it');
    }
  }
}
// AND THE ELIGIBLE SET IS NOT EMPTY. A projection that dropped `emptyKey` would
// leave every collector ineligible and a dormancy supervisor with nothing to do,
// which is exactly the state this field was added to fix.
{
  const eligible = registry.filter((c) => c.emptyKey.length && c.disableable);
  if (eligible.length < 10) {
    throw new Error(`only ${eligible.length} collectors are eligible for dormancy; the live `
      + 'filter `emptyKey && disableable` selects far more, so the projection is losing a field');
  }
}

const R = (collection) => ({ id: 'r1', host: '198.51.100.1', collection });

const CASES = [
  ['defaults: no settings, no record', {}, {}],
  ['a global interval', { pollSystem: 4000 }, {}],
  ['a router override beats the global',
    { pollSystem: 4000 }, R({ overrides: { pollSystem: 9000 } })],
  ['an override with no global at all', {}, R({ overrides: { pollSystem: 9000 } })],

  // DELIVERY. Mode is the router's; overrides beat it; neither touches intervals.
  ['mode poll', { pollSystem: 4000 }, R({ mode: 'poll' })],
  ['mode stream', {}, R({ mode: 'stream' })],
  ['an unknown mode falls back to stream', {}, R({ mode: 'sideways' })],
  ['a stream override, boolean', {}, R({ mode: 'poll', overrides: { streamSystem: true } })],
  // THE STRING FORM IS ACCEPTED TOO — `=== true || === 'true'`. A port reading
  // only the boolean would silently ignore a value a form submitted.
  ['a stream override, the STRING true', {}, R({ mode: 'poll', overrides: { streamSystem: 'true' } })],
  ['a stream override, false', {}, R({ overrides: { streamSystem: false } })],
  ['a stream override, the STRING false', {}, R({ overrides: { streamSystem: 'false' } })],

  // ENABLEMENT and the cascade.
  ['one collector off', {}, R({ off: ['wifi'] })],
  // `conns`, not `connections` — the registry key. Naming it wrongly makes the
  // case a no-op that still looks like cascade coverage, which is how this was
  // caught: the believability check demanded the cascade fire and it had not.
  ['a collector others depend on, off', {}, R({ off: ['conns'] })],
  ['several off', {}, R({ off: ['wifi', 'capsman', 'conns'] })],
  ['off names something undisableable', {}, R({ off: ['traffic'] })],
  ['off names something unknown', {}, R({ off: ['nosuchcollector'] })],
  ['the ping kill switch', { pingEnabled: false }, {}],
  ['the ping kill switch beats an explicit on', { pingEnabled: false }, R({ off: [] })],

  // pollIfaces — a metadata interval with no registry row of its own.
  ['pollIfaces from settings', { pollIfaces: 30000 }, {}],
  ['pollIfaces overridden', { pollIfaces: 30000 }, R({ overrides: { pollIfaces: 15000 } })],
  ['pollIfaces absent takes 60000', {}, {}],

  // MALFORMED INPUT. A hand-edited routers.json must not reach a collector.
  ['a non-numeric interval', { pollSystem: 'soon' }, {}],
  ['a negative interval', { pollSystem: -5 }, {}],
  ['an absurdly large interval', { pollSystem: 99999999 }, {}],
  ['a fractional interval', { pollSystem: 1500.7 }, {}],
  ['off is not an array', {}, R({ off: 'wifi' })],
  ['overrides is not an object', {}, R({ overrides: 'nope' })],
  ['collection is null', {}, { id: 'r1', collection: null }],
  ['the record is null', {}, null],

  // ---- THE FINGERPRINT'S EXTRAS ------------------------------------------
  //
  // `collectionFingerprint` folds in four settings and two record fields that
  // are NOT part of `collection` but still change how a session is built. They
  // are varied here so the fingerprint cases below can tell them apart; the
  // resolution is identical across them, which is itself the point — two routers
  // that RESOLVE the same can still need different sessions.
  //
  // THE TWO GROUPS COERCE DIFFERENTLY, and that is the trap. The record fields
  // use `rec[k] || ''`, so a `0` or an empty string both become ''. The settings
  // use `cfg[k] === undefined ? '' : cfg[k]`, so a `0` stays `0`. A port that
  // spelled both the same way would agree on every value except zero.
  ['a record defaultIf', {}, { id: 'r1', defaultIf: 'sfp1' }],
  ['a record pingTarget', {}, { id: 'r1', pingTarget: '198.51.100.9' }],
  ['both record extras', {}, { id: 'r1', defaultIf: 'sfp1', pingTarget: '1.1.1.1' }],
  ['a record extra that is EMPTY', {}, { id: 'r1', defaultIf: '' }],
  ['a record extra that is ZERO', {}, { id: 'r1', defaultIf: 0 }],
  ['settings topN', { topN: 25 }, {}],
  ['settings topTalkersN', { topTalkersN: 10 }, {}],
  ['settings maxConns', { maxConns: 5000 }, {}],
  ['settings historyMinutes', { historyMinutes: 120 }, {}],
  ['every settings extra', { topN: 25, topTalkersN: 10, maxConns: 5000, historyMinutes: 120 }, {}],
  ['a settings extra that is ZERO', { topN: 0 }, {}],
  ['a settings extra that is FALSE', { topN: false }, {}],
];

const cases = CASES.map(([name, settings, record]) => ({
  name,
  settings,
  record,
  want: resolveCollection(settings, record),
  fingerprint: collectionFingerprint(settings, record),
}));

// ---- BELIEVABILITY --------------------------------------------------------
//
// A corpus where every case resolved identically would be a corpus of the
// defaults, and a Go port returning a constant could pass it.
{
  const shapes = new Set(cases.map((c) => JSON.stringify(c.want)));
  assert.ok(shapes.size >= 12,
    'only ' + shapes.size + ' distinct resolutions across ' + CASES.length +
    ' cases — the matrix is not discriminating');

  // MOST OF THE MALFORMED CASES *SHOULD* COLLAPSE ONTO THE DEFAULT, and that is
  // the contract rather than a weakness in the corpus: a hand-edited
  // routers.json naming a collector that does not exist, or an `off` that is a
  // string, must be IGNORED, not honoured. Asserting the collapse is stronger
  // than counting distinct shapes — an earlier version of this block demanded 25
  // distinct resolutions from 29 cases and failed on correct behaviour.
  const want = (n) => cases.find((c) => c.name === n).want;
  const dflt = JSON.stringify(want('defaults: no settings, no record'));
  for (const n of ['off names something unknown', 'off is not an array',
                   'overrides is not an object', 'collection is null', 'the record is null']) {
    assert.equal(JSON.stringify(want(n)), dflt,
      'malformed input (' + n + ') changed the resolution — it must be ignored, not honoured');
  }
  // And the DISCRIMINATING ones must genuinely differ from it, or the collapse
  // above would be the whole corpus.
  for (const n of ['a global interval', 'mode poll', 'one collector off', 'the ping kill switch']) {
    assert.notEqual(JSON.stringify(want(n)), dflt,
      n + ' resolved identically to the default — that case is testing nothing');
  }

  const base = want('defaults: no settings, no record');
  assert.ok(Object.keys(base.poll).length > 10, 'the resolution carries no poll map');
  // THE CASCADE MUST ACTUALLY FIRE, or the case pinning it proves nothing.
  const dep = want('a collector others depend on, off');
  const offByCascade = Object.keys(base.enabled)
    .filter((k) => base.enabled[k] && !dep.enabled[k] && k !== 'conns');
  assert.deepEqual(offByCascade, ['bandwidth'],
    'turning off `conns` was expected to cascade to exactly `bandwidth`; it disabled ' +
    JSON.stringify(offByCascade) + '. If the registry grew an edge, widen this — but a cascade ' +
    'that stopped firing is the failure this guards.');
  // THE FINGERPRINT MUST DISCRIMINATE, or a Go port returning a constant passes.
  const fps = new Set(cases.map((c) => c.fingerprint));
  assert.ok(fps.size >= 20,
    'only ' + fps.size + ' distinct fingerprints across ' + cases.length + ' cases');
  // Two cases that RESOLVE identically but must FINGERPRINT differently — the
  // whole reason the extras are folded in.
  const a = cases.find((c) => c.name === 'settings topN');
  const b = cases.find((c) => c.name === 'defaults: no settings, no record');
  assert.equal(JSON.stringify(a.want), JSON.stringify(b.want),
    'the topN case was expected to resolve identically to the default');
  assert.notEqual(a.fingerprint, b.fingerprint,
    'a settings key outside `collection` did not change the fingerprint — then a router edit ' +
    'that alters it would skip the session rebuild it needs');
  // And the zero/empty asymmetry between the two groups.
  const recZero = cases.find((c) => c.name === 'a record extra that is ZERO');
  const recEmpty = cases.find((c) => c.name === 'a record extra that is EMPTY');
  assert.equal(recZero.fingerprint, recEmpty.fingerprint,
    'a record extra of 0 and of "" fingerprinted differently; `rec[k] || \'\'` makes them the same');
  const setZero = cases.find((c) => c.name === 'a settings extra that is ZERO');
  assert.notEqual(setZero.fingerprint, b.fingerprint,
    'a settings extra of 0 fingerprinted as absent; `=== undefined ? \'\' : cfg[k]` keeps the 0');

  // And the ping switch must be observable.
  const ping = want('the ping kill switch');
  assert.equal(ping.enabled.ping, false, 'pingEnabled:false did not disable ping');
  assert.equal(base.enabled.ping, true, 'ping is off by default — the switch case proves nothing');
}

// TWO FILES, for the reason the header gives.
//
// The TABLES are an EMBEDDED ASSET, not a Go literal — the same arrangement
// `internal/store` uses for `settings_tables.json`. A hand-written Go copy of a
// 27-row registry is a transcription error waiting to happen, and embedding it
// removes the possibility rather than testing for it. `POLL_BOUNDS` rides along
// because the clamp needs it and it is settings data, not collector data.
const { POLL_BOUNDS } = require(path.join(LIVE, 'src', 'settings.js'));
assert.ok(POLL_BOUNDS && Object.keys(POLL_BOUNDS).length > 10,
  'settings.js no longer exports POLL_BOUNDS, which the clamp needs');

// ── WHAT `GET /api/collectors` SENDS, from the live route's own expression ──
//
// `index.js` serves that route as a filter and a map over this registry. Copied
// here rather than described, so the Go handler is compared against what the
// original computes rather than against a second reading of it.
const apiCollectors = COLLECTORS
  .filter((c) => c.disableable)
  .map((c) => ({ key: c.key, label: c.label, requires: c.requires || [] }));
// `requires` MUST be an array on every row. The Go handler sends it straight
// through with no nil guard, because this line guarantees there is nothing to
// guard against — a null here would reach the dialog, which iterates it without
// checking.
for (const c of registry) {
  assert.ok(Array.isArray(c.requires),
    'registry row ' + c.key + ' has a non-array `requires`; the Go handler forwards it unguarded');
}
assert.ok(apiCollectors.length > 5 && apiCollectors.length < COLLECTORS.length,
  'the disableable filter selected ' + apiCollectors.length + ' of ' + COLLECTORS.length +
  ' collectors — a filter that keeps everything, or nothing, is not being exercised');

// ── THE #105 MIGRATION, the other half of LOOP.md 0g ──────────────────────
//
// `planMigration(settings, routers)` maps the RETIRED app-global stream/poll
// keys onto per-router `collection` blocks. It runs once per install, guarded by
// `collectionMigrated`, and after cutover the Node code holding it is gone — so
// an install that skipped that version would silently revert from Poll to
// Stream, which is the live comment's own warning: "Without this, anyone running
// global Poll would silently revert to Stream on upgrade."
//
// PURE, so it is driven directly rather than through a temp DATA_DIR. The cases
// are chosen for the branches, each of which fails differently:
//
//   - no legacy keys at all      -> [] (the common case; a modern install)
//   - all TRUE                   -> [] (already the new default; writing a block
//                                       would pin every router to a value the
//                                       operator never chose)
//   - all FALSE                  -> mode:'poll' for every router
//   - MIXED                      -> mode:'stream' plus per-collector overrides
//   - a router with its own mode -> left alone, always
//
// The last one is the one with teeth: an explicit per-router choice must never
// be overwritten by a global that no longer has a UI.
const LEGACY = mod.LEGACY_STREAM_KEYS;
assert.ok(LEGACY && Object.keys(LEGACY).length === 5,
  'LEGACY_STREAM_KEYS is not the five keys this corpus was built against');

const migFleet = [
  { id: 'r-plain' },
  { id: 'r-pinned', collection: { mode: 'poll' } },
  { id: 'r-block-no-mode', collection: { overrides: { streamPing: false } } },
];

const migration = [
  { name: 'no legacy keys', settings: {}, routers: migFleet },
  {
    name: 'all true — already the default',
    settings: { streamSystem: true, streamPing: true, streamConns: true,
      streamTalkers: true, streamIfrates: true },
    routers: migFleet,
  },
  {
    name: 'all false — every unpinned router goes to poll',
    settings: { streamSystem: false, streamPing: false, streamConns: false,
      streamTalkers: false, streamIfrates: false },
    routers: migFleet,
  },
  {
    name: 'mixed — stream with the polled ones recorded as overrides',
    settings: { streamSystem: true, streamPing: false, streamConns: false,
      streamTalkers: true, streamIfrates: true },
    routers: migFleet,
  },
  {
    // Only SOME keys present, and the ones present are all false. `present` is
    // the filter, so this is all-off over a subset rather than mixed.
    name: 'a subset of keys, all false',
    settings: { streamPing: false, streamConns: false },
    routers: migFleet,
  },
  {
    // NON-BOOLEANS ARE NOT KEYS. `typeof cfg[k] === 'boolean'` is the filter, so
    // a settings file holding the string "false" has NO legacy keys at all and
    // migrates nothing — the opposite of what the `dccbf62` coercion class would
    // suggest, and worth pinning precisely because it is the opposite.
    name: 'the strings "true"/"false" are not booleans',
    settings: { streamSystem: 'false', streamPing: 'true' },
    routers: migFleet,
  },
  { name: 'an empty fleet', settings: { streamPing: false }, routers: [] },
].map((c) => ({ ...c, plan: mod.planMigration(c.settings, c.routers) }));

// The corpus must exercise both write branches, or a port could satisfy it by
// returning [] for everything.
assert.ok(migration.some((c) => c.plan.some((p) => p.collection.mode === 'poll')),
  'no case produced a poll plan');
assert.ok(migration.some((c) => c.plan.some((p) => p.collection.mode === 'stream')),
  'no case produced a stream plan');
// AND THE PINNED ROUTER IS NEVER IN A PLAN.
for (const c of migration) {
  for (const p of c.plan) {
    assert.notStrictEqual(p.id, 'r-pinned',
      c.name + ': a router with its own mode was included in the plan');
  }
}

const artefacts = [
  [path.join(ROOT, 'internal', 'collection', 'collection_tables.json'),
    { registry, pollBounds: POLL_BOUNDS }],
  [path.join(ROOT, 'testdata', 'collection-cases.json'),
    { cases, apiCollectors, legacyStreamKeys: LEGACY, migration }],
];

let stale = 0;
for (const [file, data] of artefacts) {
  const text = JSON.stringify(data, null, 2) + '\n';
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (have !== text) {
      console.error('collection-cases: STALE — ' + path.relative(ROOT, file));
      stale++;
    }
  } else {
    fs.writeFileSync(file, text);
  }
}
if (process.argv.includes('--check')) {
  if (stale) {
    console.error('regenerate with `node tools/collection-cases.js`');
    process.exit(1);
  }
  console.log('collection-cases: ' + cases.length + ' cases, ' + registry.length + ' collectors current');
} else {
  console.log('collection-cases: wrote ' + cases.length + ' cases and ' + registry.length + ' collectors');
}
