'use strict';
/**
 * Connections cases — what the LIVE collector makes of the captured connection
 * table, for the Go port to reproduce.
 *
 * A GENERATOR RATHER THAN A GOLDEN, for the same reason bandwidth has one: this
 * collector fills a cache and emits from a debounced commit, so the replay
 * harness has no snapshot payload to pin. The rows are the same 431 the `conns`
 * fixture holds — the real thing a real router sent.
 *
 * GEO AND ASN ARE OFF, and that is the honest starting point rather than a
 * limitation of the harness. `geo.available()` is false wherever the MaxMind
 * database is absent, and the LIVE APP degrades exactly this way: no country, no
 * city, no org, no per-country breakdown. Porting the MaxMind reader is its own
 * item (PLAN.md names it a risk), and until it lands both implementations are
 * compared in the state a router without the database is already in.
 *
 * TWO CASES, because the cap changes the answer: one unrestricted, and one with
 * `maxConns` set below the row count so `processingCapped` is exercised.
 *
 *   node tools/conns-cases.js            write testdata/conns-cases.json
 *   node tools/conns-cases.js --check    exit 1 if stale
 */

const fs = require('node:fs');
const path = require('node:path');

const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(__dirname, '..', '..', 'MikroDash'));
const OUT = path.join(__dirname, '..', 'testdata', 'conns-cases.json');
const FIXTURE = path.join(__dirname, '..', 'testdata', 'fixtures',
  'Mikrotik identity-0cc5 AX3', 'conns.json');

const ConnectionsCollector = require(path.join(LIVE, 'src', 'collectors', 'connections.js'));

/**
 * The LAN is HALF the captured range, and it has to be.
 *
 * The fixture anonymiser maps every address — LAN hosts and internet endpoints
 * alike — into 198.51.100.0/24, so with that whole /24 as the LAN nothing looks
 * external and the destination half of this collector produces literally
 * nothing: zero top destinations, zero per-country data, zero per-source
 * destination indexes. Splitting the range at /25 gives the fixture an inside
 * and an outside — 28 sources in the low half, 63 destinations in the high half,
 * 75 rows crossing between them — and both implementations are handed the same
 * rule, which is all a differential gate needs.
 */
const LAN = ['198.51.100.0/25'];

/** The collector's world, stubbed down to what it reads. */
function harness(maxConns, detailed) {
  const rooms = new Map();
  // The per-country and per-source indexes are built ONLY when the Connections
  // page has a viewer, which the collector tests by asking the room for its
  // size. Both states are generated, because "empty because nobody is looking"
  // and "empty because there is nothing" are different answers.
  if (detailed) rooms.set('page-connections', new Set([1]));
  const chain = { to() { return this; }, emit() {} };
  return {
    ros: { connected: true, routerLabel: 'cases', on() {} },
    io: {
      engine: { clientsCount: 1 },
      to() { return chain; },
      emit() {},
      sockets: { adapter: { rooms } },
    },
    state: {},
    pollMs: 3000,
    topN: 10,
    maxConns,
    streamMode: false,
    dhcpNetworks: { getLanCidrs: () => LAN },
    // STUBS THAT ANSWER NOTHING, not nulls. `resolveName` here calls
    // `dhcpLeases.getNameByIP` UNGUARDED — unlike bandwidth's `_resolveName`,
    // which tests for the collector first — so a null throws. Answering nothing
    // is also the honest case: a router that is not its clients' DHCP server has
    // no name for them, and the collector then names a source BY ITS IP rather
    // than leaving it blank.
    dhcpLeases: { getNameByIP: () => null, getNameByMAC: () => null },
    arp: { getByIP: () => null },
    // Explicitly off. See the header.
    geoLookup: null,
    connTableCache: null,
    geoOrgCache: { geo: new Map(), org: new Map() },
  };
}

async function build(rows, maxConns, detailed) {
  const c = new ConnectionsCollector(harness(maxConns, detailed));
  await c._processRows(rows);
  return c.lastPayload;
}

async function main() {
  const check = process.argv.includes('--check');
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'));
  const rows = (fixture.exchanges || []).flatMap((e) => e.rows || []);
  if (!rows.length) throw new Error('the conns fixture holds no rows');

  const full = await build(rows, 10000, true);
  const capped = await build(rows, 100, true);
  const noDetail = await build(rows, 10000, false);

  // `ts` is wall-clock and `newSinceLast` counts against the PREVIOUS tick, so
  // neither can be part of a contract a second implementation reproduces.
  const strip = (p) => {
    const out = { ...p };
    delete out.ts;
    delete out.newSinceLast;
    return out;
  };

  const cases = {
    note: 'Generated by tools/conns-cases.js — do not edit. Geo and ASN are OFF; see the header.',
    lanCidrs: LAN, topN: 10, rows: rows.length,
    full: strip(full),
    capped: { maxConns: 100, ...strip(capped) },
    // The same rows with no Connections page open: the per-country and
    // per-source indexes must be EMPTY, not merely unused.
    noDetail: strip(noDetail),
  };

  const body = JSON.stringify(cases, null, 2) + '\n';
  if (check) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (cur !== body) {
      console.error('testdata/conns-cases.json is stale — run: node tools/conns-cases.js');
      process.exit(1);
    }
    console.log('conns cases up to date (' + cases.full.topSources.length + ' top sources, ' +
      cases.full.topDestinations.length + ' top destinations)');
    return;
  }
  fs.writeFileSync(OUT, body);
  console.log('wrote ' + path.relative(path.join(__dirname, '..'), OUT) +
    ' — ' + rows.length + ' rows, ' + cases.full.topSources.length + ' top sources, ' +
    cases.full.topDestinations.length + ' top destinations, ' +
    Object.keys(cases.full.sourceDests).length + ' sources with a destination index');
}

main().catch((e) => { console.error(e); process.exit(1); });
