'use strict';
/**
 * The extra cards' two lookup tables, lifted from public/app.js.
 *
 *   DC_CC_NAMES    98 country codes -> names. A CONDENSED subset of the
 *                  connections page's own CC_NAMES, and deliberately not the
 *                  same table: the card falls back to the payload's `country`
 *                  and then to the bare code, so a country missing here still
 *                  renders something.
 *   DC_PORT_NAMES  30 well-known ports -> service names.
 *
 * ── GENERATED FOR THE SAME REASON AS THE GRID TABLES ────────────────────────
 *
 * 128 string pairs. Transcribing them by hand puts a wrong country name on a
 * card, which nothing would flag — it would simply be the label.
 *
 * ── THE CHECKS ──────────────────────────────────────────────────────────────
 *
 * Every country key is a two-letter upper-case code, since `dcFlag` maps exactly
 * two characters and anything else silently becomes a globe; and every port key
 * parses as a port number, because the lookup is by `String(p.port)` and a key
 * that is not a number could never be hit.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/dccards-tables.js [--check]
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const src = fs.readFileSync(path.join(LIVE, 'public', 'app.js'), 'utf8');
const OUT = path.join(ROOT, 'web', 'src', 'gen', 'dccards-tables.ts');

function grab(decl, close, name) {
  const i = src.indexOf(decl);
  if (i === -1) throw new Error('cannot find ' + name);
  const j = src.indexOf(close, i);
  if (j === -1) throw new Error(name + ' is never closed');
  return src.slice(i, j + close.length);
}
const ctx = {};
vm.createContext(ctx);
vm.runInContext([
  grab('var DC_CC_NAMES={', '};', 'DC_CC_NAMES'),
  grab('var DC_PORT_NAMES=', '};', 'DC_PORT_NAMES'),
].join('\n'), ctx);

const { DC_CC_NAMES, DC_PORT_NAMES } = ctx;
assert.ok(Object.keys(DC_CC_NAMES).length > 80, 'only ' + Object.keys(DC_CC_NAMES).length + ' countries');
assert.ok(Object.keys(DC_PORT_NAMES).length > 20, 'only ' + Object.keys(DC_PORT_NAMES).length + ' ports');

for (const cc of Object.keys(DC_CC_NAMES)) {
  assert.match(cc, /^[A-Z]{2}$/,
    'country key ' + JSON.stringify(cc) + ' is not a two-letter upper-case code — dcFlag maps ' +
    'exactly two characters and anything else silently renders a globe');
}
for (const p of Object.keys(DC_PORT_NAMES)) {
  assert.match(p, /^\d+$/,
    'port key ' + JSON.stringify(p) + ' is not numeric — the lookup is by String(p.port), so a ' +
    'non-numeric key could never be hit');
  assert.ok(Number(p) >= 1 && Number(p) <= 65535, 'port ' + p + ' is out of range');
}

const j = (v) => JSON.stringify(v, null, 2);
const body = `// GENERATED by tools/dccards-tables.js — do not edit.
//
// The extra cards' lookup tables, lifted from public/app.js. See that tool for
// why they are extracted rather than typed, and what it checks before emitting.
//
//   MIKRODASH_SRC=../MikroDash node tools/dccards-tables.js

/**
 * Country code to name. A CONDENSED subset of the connections page's CC_NAMES
 * and deliberately not the same table — the card falls back to the payload's
 * own \`country\` and then to the bare code, so a country missing here still
 * renders something.
 */
export const DC_CC_NAMES: Readonly<Record<string, string>> = ${j(DC_CC_NAMES)};

/** Well-known port to service name. Missing ports render an empty label. */
export const DC_PORT_NAMES: Readonly<Record<string, string>> = ${j(DC_PORT_NAMES)};
`;

if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== body) {
    console.error('web/src/gen/dccards-tables.ts is stale — run: node tools/dccards-tables.js');
    process.exit(1);
  }
  console.log('dccards-tables: up to date (%d countries, %d ports)',
    Object.keys(DC_CC_NAMES).length, Object.keys(DC_PORT_NAMES).length);
} else {
  fs.writeFileSync(OUT, body);
  console.log('dccards-tables: wrote %d countries and %d ports',
    Object.keys(DC_CC_NAMES).length, Object.keys(DC_PORT_NAMES).length);
}
