'use strict';
/**
 * The DORMANCY STATE MACHINE, as a corpus generated by RUNNING the live
 * `createDormancyState` from `src/collectors/util.js`.
 *
 * ---- WHY IT IS WORTH PORTING NOW ------------------------------------------
 *
 * `collection:status` is the last event a live-verified sweep still shows this
 * port never sending, and its client-side consumer `applyCollectionStatus` is
 * written, gated by `tools/stale-check.js`, and called by nothing —
 * `tools/orphaned-consumer-audit.js` holds that ledger. The event reports which
 * collectors the DORMANCY SUPERVISOR has put to sleep, and this port has no
 * supervisor. This is its decision half, which is pure: observations in, verdict
 * out, no timers and no I/O.
 *
 * That makes it the same shape as the write guards — "the decision lives in one
 * pure module rather than inline in six handlers" — and the same cheapness.
 *
 * ---- SEQUENCES, NOT CASES -------------------------------------------------
 *
 * It is a state machine, so a corpus of independent inputs would pin almost
 * nothing: `observe` returns 'sleep' only on the THIRD consecutive empty, and a
 * probe that comes back empty doubles a delay that then caps. Each case here is
 * an ORDERED sequence of steps, and every step records the verdict AND all five
 * getters, so a port that reaches the right answer through the wrong state is
 * still caught.
 *
 * ---- `now` IS SUPPLIED, NEVER TAKEN -------------------------------------
 *
 * Every method takes `now` with a `Date.now()` default. The corpus passes it
 * explicitly at every step: a generated file that called the clock would differ
 * on every run and `--check` would be permanently stale, which is the trap
 * `tools/routers-public-cases.js` fell into.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/dormancy-cases.js
 *   MIKRODASH_SRC=../MikroDash node tools/dormancy-cases.js --check
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const OUT = path.join(ROOT, 'testdata', 'dormancy-cases.json');

const { createDormancyState } = require(path.join(LIVE, 'src', 'collectors', 'util.js'));

// The live defaults, restated so the corpus records what it ran with and the Go
// side can assert it uses the same. Passing them explicitly ALSO exercises the
// destructuring, which a `createDormancyState()` with no argument would not.
const DEFAULTS = {
  emptyThreshold: 3,
  backoffMs: 60000,
  maxBackoffMs: 600000,
  probeTimeoutMs: 30000,
  restampMs: 45000,
};

const T0 = 1_700_000_000_000; // a fixed epoch; nothing here reads the clock

/** Run one ordered sequence and record every step. */
function run(steps, opts) {
  const st = createDormancyState(opts || DEFAULTS);
  return steps.map((s) => {
    let verdict = null;
    let due = null;
    if (s.op === 'observe') {
      verdict = st.observe(s.obs, s.now);
    } else if (s.op === 'dueForProbe') {
      due = st.dueForProbe(s.now);
    } else if (s.op === 'markProbed') {
      st.markProbed(s.now);
    } else if (s.op === 'reset') {
      st.reset();
    } else {
      throw new Error('unknown op ' + s.op);
    }
    return {
      ...s,
      verdict,
      due,
      // ALL FIVE GETTERS after every step. A port that returns the right verdict
      // from the wrong internal state fails on the step after.
      state: { dormant: st.dormant, probing: st.probing, streak: st.streak,
               delayMs: st.delayMs, wakeAt: st.wakeAt },
    };
  });
}

const ob = (n, o) => ({ op: 'observe', now: n, obs: o });

const CASES = [
  {
    why: 'three consecutive empties put it to sleep, and not the second',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: true }),
    ]),
  },
  {
    why: 'a non-empty payload resets the streak, so the next two empties are not enough',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: false }),
      ob(T0 + 3000, { ts: 4, empty: true }),
      ob(T0 + 4000, { ts: 5, empty: true }),
    ]),
  },
  {
    // UNSUPPORTED skips the streak entirely and sleeps for the MAXIMUM, not the
    // base delay. A port that treated it as one more empty would re-probe a menu
    // this RouterOS does not have every minute forever.
    why: 'unsupported sleeps immediately, and for maxBackoffMs rather than backoffMs',
    steps: run([ob(T0, { ts: 1, unsupported: true })]),
  },
  {
    why: 'a fresh non-empty payload wakes it, and returns "wake" exactly once',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: true }),
      ob(T0 + 3000, { ts: 4, empty: false }),
      ob(T0 + 4000, { ts: 5, empty: false }),
    ]),
  },
  {
    // A PROBE THAT COMES BACK EMPTY doubles the delay rather than re-announcing
    // sleep — the verdict is null, and only the delay moves.
    why: 'an empty probe doubles the delay and does not re-announce sleep',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: true }),
      ob(T0 + 3000, { ts: 4, empty: true }),
      ob(T0 + 4000, { ts: 5, empty: true }),
      ob(T0 + 5000, { ts: 6, empty: true }),
    ]),
  },
  {
    // THE CAP. Doubling from 60s reaches 600s and stops: 60, 120, 240, 480, 600.
    why: 'the delay doubles to maxBackoffMs and stops there',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: true }),
      ...[4, 5, 6, 7, 8, 9].map((i) => ob(T0 + i * 1000, { ts: i, empty: true })),
    ]),
  },
  {
    // A REPEATED ts is not evidence — the collector produced nothing new — but a
    // payload held EMPTY for restampMs is. This is the rule that made dormancy
    // work for the five heartbeat collectors whose ts freezes.
    why: 'a repeated ts is ignored until restampMs has passed, then it counts',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 1, empty: true }),        // too soon: ignored
      ob(T0 + 44000, { ts: 1, empty: true }),       // still < 45s from lastCountedAt
      ob(T0 + 46000, { ts: 1, empty: true }),       // >= restampMs: counts
      ob(T0 + 92000, { ts: 1, empty: true }),       // counts again -> asleep
    ]),
  },
  {
    why: 'an observation with no ts is ignored entirely, whatever else it says',
    steps: run([
      ob(T0, { ts: 0, empty: true }),
      ob(T0 + 1000, { ts: 1, empty: true }),
    ]),
  },
  {
    // dueForProbe is false while awake, true once wakeAt passes, and a probe
    // that never reported back is SETTLED by it — backOff, still asleep.
    why: 'dueForProbe: false while awake, true at wakeAt, and it settles a timed-out probe',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      { op: 'dueForProbe', now: T0 + 1500 },        // awake: false
      ob(T0 + 2000, { ts: 3, empty: true }),        // asleep, wakeAt = +62000
      { op: 'dueForProbe', now: T0 + 3000 },        // too early
      { op: 'dueForProbe', now: T0 + 62000 },       // due
      { op: 'markProbed', now: T0 + 62000 },
      { op: 'dueForProbe', now: T0 + 80000 },       // probing, deadline not reached
      { op: 'dueForProbe', now: T0 + 95000 },       // deadline passed: settles, false
      { op: 'dueForProbe', now: T0 + 95001 },       // no longer probing, not yet due
    ]),
  },
  {
    why: 'reset forgets everything, including the doubled delay',
    steps: run([
      ob(T0, { ts: 1, unsupported: true }),
      { op: 'reset', now: T0 + 1000 },
      { op: 'dueForProbe', now: T0 + 2000 },
      ob(T0 + 3000, { ts: 2, empty: true }),
    ]),
  },
  {
    // A ZERO ts ARRIVING AFTER A REAL ONE. The first version of this corpus had
    // only a zero ts as the FIRST observation, where `lastTS` is also 0 — so the
    // guard and its absence agree (not fresh, nothing counted yet, both return
    // null) and removing `if (!obs.ts) return null` SURVIVED. The discriminating
    // shape is a zero arriving late enough that the restamp rule would otherwise
    // count it.
    why: 'a zero ts is ignored even when a real one preceded it and restampMs has passed',
    steps: run([
      ob(T0, { ts: 7, empty: true }),
      ob(T0 + 50000, { ts: 0, empty: true }),
      ob(T0 + 100000, { ts: 0, empty: true }),
    ]),
  },
  {
    // WAKING FROM A DOUBLED DELAY. Every wake above happened at the base delay,
    // so dropping `delay = backoffMs` from the wake arm SURVIVED: the value was
    // already 60000. This one backs off twice first, so the reset is visible.
    why: 'waking resets the delay to backoffMs, not to whatever the backoff reached',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),
      ob(T0 + 2000, { ts: 3, empty: true }),      // asleep, delay 60000
      ob(T0 + 3000, { ts: 4, empty: true }),      // probe empty -> 120000
      ob(T0 + 4000, { ts: 5, empty: true }),      // -> 240000
      ob(T0 + 5000, { ts: 6, empty: false }),     // wake: delay back to 60000
    ]),
  },
  {
    // RESET WITH A STREAK TO FORGET. The reset case below resets after
    // `unsupported`, which leaves the streak at 0 already — so dropping
    // `streak = 0` from reset() SURVIVED. Two empties first, then the reset, then
    // two more: if the streak survived, the FIRST of those two would sleep.
    why: 'reset forgets a partial empty streak, so the count starts again',
    steps: run([
      ob(T0, { ts: 1, empty: true }),
      ob(T0 + 1000, { ts: 2, empty: true }),      // streak 2
      { op: 'reset', now: T0 + 1500 },
      ob(T0 + 2000, { ts: 3, empty: true }),      // streak 1, NOT sleep
      ob(T0 + 3000, { ts: 4, empty: true }),      // streak 2, still not sleep
    ]),
  },
  {
    // NON-DEFAULT OPTIONS, because a port that hard-codes 3 and 60000 passes
    // every case above.
    why: 'the options are honoured: a threshold of 1 and a 10s backoff',
    steps: run([ob(T0, { ts: 1, empty: true })],
      { ...DEFAULTS, emptyThreshold: 1, backoffMs: 10000, maxBackoffMs: 40000 }),
  },
];

// ---- Believability ---------------------------------------------------------
const byWhy = Object.fromEntries(CASES.map((c) => [c.why, c]));
const need = (k) => {
  if (!byWhy[k]) throw new Error(`a believability check names a case that is gone: ${k}`);
  return byWhy[k];
};
const verdicts = CASES.flatMap((c) => c.steps.map((s) => s.verdict));

// THE CORPUS MUST DISCRIMINATE. One that never sleeps, or never wakes, agrees
// with a state machine that does nothing.
if (!verdicts.includes('sleep')) throw new Error('no case ever reaches sleep');
if (!verdicts.includes('wake')) throw new Error('no case ever wakes');
if (!verdicts.includes(null)) throw new Error('every step returns a verdict; none is a no-op');

// THE THRESHOLD IS REAL: the third empty sleeps and the second does not.
{
  const s = need('three consecutive empties put it to sleep, and not the second').steps;
  if (s[1].verdict !== null) throw new Error('the SECOND empty announced sleep');
  if (s[2].verdict !== 'sleep') throw new Error('the third empty did not announce sleep');
  if (s[1].state.streak !== 2) throw new Error(`streak after two empties is ${s[1].state.streak}`);
}
// UNSUPPORTED sleeps at the MAXIMUM, which is the arm a port collapses into the
// empty one.
{
  const s = need('unsupported sleeps immediately, and for maxBackoffMs rather than backoffMs').steps;
  if (s[0].verdict !== 'sleep') throw new Error('unsupported did not sleep at once');
  if (s[0].state.delayMs !== DEFAULTS.maxBackoffMs) {
    throw new Error(`unsupported slept for ${s[0].state.delayMs}, not maxBackoffMs — if these two `
      + 'are equal the case cannot tell the arms apart');
  }
}
// THE CAP is actually reached, or the doubling case proves only that it doubles.
{
  const s = need('the delay doubles to maxBackoffMs and stops there').steps;
  const last = s[s.length - 1].state.delayMs;
  if (last !== DEFAULTS.maxBackoffMs) {
    throw new Error(`the delay reached ${last}, not the cap — extend the sequence`);
  }
  const seen = new Set(s.map((x) => x.state.delayMs));
  if (seen.size < 4) throw new Error('the delay barely moved; this case is not exercising backoff');
}
// THE RESTAMP RULE fires, or the case is only testing that repeats are ignored.
{
  const s = need('a repeated ts is ignored until restampMs has passed, then it counts').steps;
  if (s[1].state.streak !== s[0].state.streak) throw new Error('a too-soon repeat was counted');
  if (s[3].state.streak <= s[2].state.streak) {
    throw new Error('the repeat after restampMs was NOT counted — the rule is not exercised');
  }
}
// A PROBE IS ACTUALLY SETTLED, which is dueForProbe's side effect and the part a
// port implements as a pure predicate by mistake.
{
  const s = need('dueForProbe: false while awake, true at wakeAt, and it settles a timed-out probe').steps;
  const probed = s.filter((x) => x.op === 'dueForProbe');
  if (!probed.some((x) => x.due === true)) throw new Error('dueForProbe never returned true');
  const settling = s.find((x) => x.op === 'dueForProbe' && x.now === T0 + 95000);
  if (settling.state.probing !== false) {
    throw new Error('the timed-out probe was not settled — dueForProbe has a side effect and this '
      + 'case exists to pin it');
  }
}
// THE OPTIONS ARE HONOURED, or a port with the defaults hard-coded passes.
{
  const s = need('the options are honoured: a threshold of 1 and a 10s backoff').steps;
  if (s[0].verdict !== 'sleep') throw new Error('emptyThreshold: 1 did not sleep on the first empty');
  if (s[0].state.delayMs !== 10000) throw new Error('backoffMs was not honoured');
}

// THE THREE CASES ADDED AFTER MUTATION TESTING, each pinned by the property that
// made its mutant survive. A case that stopped discriminating would be worse than
// no case, because the mutation record would still claim it was killed.
{
  const s = need('a zero ts is ignored even when a real one preceded it and restampMs has passed').steps;
  if (s[0].state.streak !== 1) throw new Error('the priming observation did not count');
  if (s[2].state.streak !== 1) {
    throw new Error(`a zero ts was COUNTED (streak ${s[2].state.streak}) — either the live guard `
      + 'changed or this sequence no longer reaches past the restamp window');
  }
}
{
  const s = need('waking resets the delay to backoffMs, not to whatever the backoff reached').steps;
  const beforeWake = s[s.length - 2].state.delayMs;
  const afterWake = s[s.length - 1].state.delayMs;
  if (beforeWake <= DEFAULTS.backoffMs) {
    throw new Error(`the delay was only ${beforeWake} before the wake, so this case cannot tell `
      + 'whether waking resets it');
  }
  if (afterWake !== DEFAULTS.backoffMs) throw new Error('waking did not reset the delay');
  if (s[s.length - 1].verdict !== 'wake') throw new Error('the last step did not wake');
}
{
  const s = need('reset forgets a partial empty streak, so the count starts again').steps;
  if (s[1].state.streak !== 2) throw new Error('the pre-reset streak is not 2');
  if (s.some((x) => x.verdict === 'sleep')) {
    throw new Error('this sequence slept, so it does not show the reset preventing one');
  }
  if (s[s.length - 1].state.streak !== 2) {
    throw new Error('the post-reset streak did not climb back to 2');
  }
}

const json = JSON.stringify(
  { generated_from: 'src/collectors/util.js createDormancyState', defaults: DEFAULTS, t0: T0,
    cases: CASES }, null, 2) + '\n';
if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== json) {
    console.error('STALE: testdata/dormancy-cases.json - re-run tools/dormancy-cases.js');
    process.exit(1);
  }
  console.log(`dormancy-cases: up to date (${CASES.length} sequences, `
    + `${CASES.reduce((n, c) => n + c.steps.length, 0)} steps)`);
} else {
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${OUT} (${CASES.length} sequences, `
    + `${CASES.reduce((n, c) => n + c.steps.length, 0)} steps)`);
}
