'use strict';
/**
 * `_PRINCIPAL_MODALS`, extracted from the live app.js.
 *
 * Every dialog in the app that closes on Escape and on a backdrop click. The
 * name is a leftover — it started as the Settings principals dialogs and the
 * live comment says plainly that it long since stopped being that: "The Router
 * Users dialogs are on their own page rather than in Settings, but Escape and
 * backdrop-click are handled here for every dialog in the app."
 *
 * ── WHY IT IS GENERATED ─────────────────────────────────────────────────────
 *
 * An earlier version of this port read the name, believed it, and wrote in a
 * comment that the list was "a Settings-page list of ids, none of them ported".
 * Four of the ten are on ported pages. The result was five dialogs with no
 * Escape and no backdrop click, and a justification that read as considered.
 * Extracting the list means the port cannot hold an opinion about what is in it.
 *
 * Each id is also checked against the extracted markup: one that is missing
 * means its page has not been extracted yet, which is worth stopping for.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/modal-list.js [--check]
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const src = fs.readFileSync(path.join(LIVE, 'public', 'app.js'), 'utf8');
const OUT = path.join(ROOT, 'testdata', 'modal-list.json');

const m = src.match(/var _PRINCIPAL_MODALS = \[([\s\S]*?)\];/);
if (!m) throw new Error('cannot find _PRINCIPAL_MODALS in public/app.js');
const all = [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]);
if (all.length < 5) throw new Error('_PRINCIPAL_MODALS parsed as ' + all.length + ' ids — shape changed');

/**
 * Every id must be in the extracted markup, and that is the whole check.
 *
 * The first version of this generator split them into "ported" and "not", and
 * both exceptions it needed turned out to be wrong: markup is extracted per page
 * and verbatim, so a dialog belonging to an unported FEATURE is still in the DOM.
 * The close behaviour does not care — it removes `.open` from an element if the
 * element exists, which is a no-op for a dialog that never opens. So the split
 * bought nothing and would have excluded two dialogs from a behaviour that is
 * correct for them.
 *
 * An id that is genuinely absent means its PAGE has not been extracted, which is
 * a different problem and worth stopping for.
 */
const ui = fs.readdirSync(path.join(ROOT, 'web', 'src', 'ui'))
  .map((f) => fs.readFileSync(path.join(ROOT, 'web', 'src', 'ui', f), 'utf8')).join('\n');

const missing = all.filter((id) => !ui.includes('id="' + id + '"'));
if (missing.length) {
  console.error('these dialogs are in _PRINCIPAL_MODALS but in no extracted page — the page ' +
    'holding them has not been extracted yet:\n  ' + missing.join('\n  ') + '\n');
  process.exit(1);
}

const body = JSON.stringify({
  note: 'Generated by tools/modal-list.js from the LIVE public/app.js. Do not edit.',
  all,
}, null, 2) + '\n';

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (cur !== body) {
    console.error('testdata/modal-list.json is stale — run: node tools/modal-list.js');
    process.exit(1);
  }
  console.log('modal list up to date (' + all.length + ' dialogs, all present in the markup)');
} else {
  fs.writeFileSync(OUT, body);
  console.log('wrote testdata/modal-list.json — ' + all.length + ' dialogs');
}
