'use strict';
/**
 * The notifier's two PURE decisions, as a corpus generated by RUNNING
 * `src/notifier.js`.
 *
 * Only two of that module's functions can be reached without sending anything:
 * `hasConfiguredChannel`, which is exported, and `_reason`, which is not — so it
 * is LIFTED by source rather than required, the same way the gate tooling lifts
 * a renderer. The transports themselves are HTTP and SMTP and are not ported.
 *
 * ---- WHY `hasConfiguredChannel` IS WORTH A CORPUS --------------------------
 *
 * Its own comment records the bug it exists to prevent: the alerter used to ask
 * "is any channel active?" from the *Enabled flags ALONE, while `send()` checked
 * flags PLUS credentials. A channel ticked without a token then "consumed the
 * alert cooldown, sent nothing, and logged nothing" — a silent failure with a
 * rate limit attached.
 *
 * So the rule is not "is it enabled" but "is it enabled AND does it have what its
 * send path needs", and the two places that ask must agree. The Go port answers
 * both from ONE function, and the corpus below carries a case per channel with
 * each required field missing in turn — the shapes that separate the two
 * readings.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/notifier-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/notifier-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const srcPath = path.join(LIVE, 'src', 'notifier.js');
const src = fs.readFileSync(srcPath, 'utf8');
const { hasConfiguredChannel } = require(srcPath);

// `_reason` is module-private. Lifted whole rather than reimplemented — the
// slice is anchored on its opening line and the dedent that ends it, and the
// assertions below refuse a slice that lost its parts.
const from = src.indexOf('function _reason(raw) {');
assert.ok(from > 0, '_reason has moved in notifier.js');
const to = src.indexOf('\n}', from);
const reasonSrc = src.slice(from, to + 2);
for (const marker of ['JSON.parse', 'j.description', '160', "' — '"]) {
  assert.ok(reasonSrc.includes(marker), 'the lifted _reason lost: ' + marker);
}
const ctx = { JSON, String };
vm.createContext(ctx);
vm.runInContext(reasonSrc + '\nglobalThis.__reason = _reason;', ctx);
const reason = ctx.__reason;

// ---- `_reason`: what a failing channel says --------------------------------
const REASONS = [
  ['nothing', ''],
  ['null', null],
  ['a bare string', 'Bad Request'],
  ['a string needing a trim', '   Bad Request   '],
  // PRECEDENCE: description, then error, then message.
  ['json description', '{"description":"chat not found"}'],
  ['json error', '{"error":"nope"}'],
  ['json message', '{"message":"nope"}'],
  ['json with all three', '{"description":"first","error":"second","message":"third"}'],
  ['json with error and message', '{"error":"second","message":"third"}'],
  ['json with none of them', '{"other":"x"}'],
  ['json that is not an object', '"just a string"'],
  ['json null', 'null'],
  ['malformed json', '{"description":'],
  // WHITESPACE IS COLLAPSED, then the result is cut at 160 characters.
  ['newlines and tabs', 'a\n\nb\t\tc'],
  ['a long body', 'x'.repeat(400)],
  ['a long json description', '{"description":"' + 'y'.repeat(400) + '"}'],
  // LONG *AND* FULL OF WHITESPACE RUNS — the only shape that observes the ORDER
  // of the two operations. Collapsing first shortens the text, so more words
  // survive the 160-character cut; cutting first keeps the runs and loses words.
  // Every other long case here has no whitespace and every whitespace case is
  // short, so the mutation that swapped them survived until this existed.
  ['long with whitespace runs', ('word' + '   \n\t  ').repeat(40)],
  ['exactly 160', 'z'.repeat(160)],
  ['161 characters', 'z'.repeat(161)],
  ['an html error page', '<html><body>\n  <h1>502 Bad Gateway</h1>\n</body></html>'],
];

// ---- `hasConfiguredChannel`: enabled AND configured ------------------------
const S = (o) => o;
const CHANNELS = [
  ['nothing at all', S({})],
  ['null settings', null],

  ['telegram complete', S({ telegramEnabled: true, telegramBotToken: 't', telegramChatId: 'c' })],
  ['telegram without a token', S({ telegramEnabled: true, telegramChatId: 'c' })],
  ['telegram without a chat id', S({ telegramEnabled: true, telegramBotToken: 't' })],
  ['telegram configured but DISABLED', S({ telegramBotToken: 't', telegramChatId: 'c' })],

  ['pushbullet complete', S({ pushbulletEnabled: true, pushbulletApiKey: 'k' })],
  ['pushbullet without a key', S({ pushbulletEnabled: true })],
  ['pushbullet configured but disabled', S({ pushbulletApiKey: 'k' })],

  ['smtp complete', S({ smtpEnabled: true, smtpHost: 'h', smtpFrom: 'f', smtpTo: 't' })],
  ['smtp without a host', S({ smtpEnabled: true, smtpFrom: 'f', smtpTo: 't' })],
  ['smtp without a from', S({ smtpEnabled: true, smtpHost: 'h', smtpTo: 't' })],
  ['smtp without a to', S({ smtpEnabled: true, smtpHost: 'h', smtpFrom: 'f' })],

  ['ntfy complete', S({ ntfyEnabled: true, ntfyUrl: 'https://ntfy.sh/x' })],
  ['ntfy without a url', S({ ntfyEnabled: true })],

  // A channel half-configured beside one that IS usable: the answer is yes, and
  // the half-configured one must not be counted.
  ['one usable, one half-configured',
    S({ telegramEnabled: true, telegramBotToken: 't', telegramChatId: 'c', ntfyEnabled: true })],
  // EMPTY STRINGS ARE FALSY, so a blank token is the same as a missing one.
  ['telegram with an empty token', S({ telegramEnabled: true, telegramBotToken: '', telegramChatId: 'c' })],
  ['enabled is the string "false"', S({ telegramEnabled: 'false', telegramBotToken: 't', telegramChatId: 'c' })],
];

const cases = {
  reasons: REASONS.map(([name, raw]) => ({ name, raw, want: reason(raw) })),
  channels: CHANNELS.map(([name, s]) => ({ name, settings: s, want: !!hasConfiguredChannel(s) })),
};

// ---- BELIEVABILITY --------------------------------------------------------
{
  const r = (n) => cases.reasons.find((c) => c.name === n).want;
  assert.equal(r('nothing'), '', 'an empty body produced a reason');
  assert.ok(r('a bare string').startsWith(' — '), 'the separator is missing');
  assert.equal(r('json with all three'), ' — first', 'description does not win');
  assert.equal(r('json with error and message'), ' — second', 'error does not beat message');
  assert.ok(r('a long body').length <= 163, 'the 160-character cut is not applied');
  assert.ok(!r('newlines and tabs').includes('\n'), 'whitespace is not collapsed');
  // The order case must actually distinguish: collapsed-then-cut keeps whole
  // words to the limit, so the result must contain no double space and must be
  // at the cut.
  const runs = r('long with whitespace runs');
  assert.ok(!runs.includes('  '), 'the long/whitespace case still contains a run');
  assert.ok(runs.length > 150, 'the long/whitespace case did not reach the cut');

  const yes = cases.channels.filter((c) => c.want).length;
  const no = cases.channels.length - yes;
  assert.ok(yes >= 5 && no >= 8,
    'the channel matrix does not discriminate: ' + yes + ' yes, ' + no + ' no');
  // THE BUG THIS GUARDS: enabled-without-credentials must be NO.
  for (const n of ['telegram without a token', 'pushbullet without a key',
                   'smtp without a host', 'ntfy without a url']) {
    assert.equal(cases.channels.find((c) => c.name === n).want, false,
      n + ' counted as configured — that is the state that consumed the cooldown and sent nothing');
  }
}

const FILE = path.join(ROOT, 'testdata', 'notifier-cases.json');
const text = JSON.stringify(cases, null, 2) + '\n';
if (process.argv.includes('--check')) {
  const have = fs.existsSync(FILE) ? fs.readFileSync(FILE, 'utf8') : '';
  if (have !== text) {
    console.error('notifier-cases: STALE — regenerate with `node tools/notifier-cases.js`');
    process.exit(1);
  }
  console.log('notifier-cases: ' + cases.reasons.length + ' reasons, ' +
    cases.channels.length + ' channel shapes current');
} else {
  fs.writeFileSync(FILE, text);
  console.log('notifier-cases: wrote ' + cases.reasons.length + ' reasons and ' +
    cases.channels.length + ' channel shapes');
}
