'use strict';
/**
 * The ping collector's arithmetic, generated by RUNNING the live one.
 *
 * ── EVERY EXPECTATION IS THE LIVE ANSWER, NOT MINE ──────────────────────────
 *
 * `_parseRtt` and the loss window are small enough to look obvious and are not:
 * a microsecond value is divided and rounded to three places, a compound
 * duration like `1ms438us` keeps only its first unit, and `echo reply` — which
 * RouterOS really does send, for a multicast ping — is NOT the string `replied`
 * and therefore counts as LOST. Each of those is a place a reasonable port
 * disagrees with the app it replaces, so the corpus is produced by driving the
 * real collector rather than by writing down what I believe it does.
 *
 * ── THE COLLECTOR IS DRIVEN THROUGH ITS OWN PACKET PATH ─────────────────────
 *
 * `_processPacket` is where rtt, loss, history and the emit fingerprint are all
 * decided together, so the cases feed it packet SEQUENCES and record what came
 * out after each one. A per-packet corpus could not see the rolling window at
 * all.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/ping-cases.js [--check]
 */

const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const OUT = path.join(ROOT, 'internal', 'collect', 'testdata', 'ping-cases.json');

const PingCollector = require(path.join(LIVE, 'src', 'collectors', 'ping.js'));

// A collector with every side effect stubbed. Only the packet path is exercised.
function makeCollector(target) {
  const emitted = [];
  const io = {
    on() {}, engine: { clientsCount: 1 },
    to() { return { emit: (ev, payload) => emitted.push({ ev, payload }) }; },
  };
  const ros = { on() {}, connected: false, routerLabel: '' };
  const c = new PingCollector({
    ros, io, pollMs: 5000, state: {}, target, streamMode: true,
  });
  return { c, emitted };
}

// ── the corpus ─────────────────────────────────────────────────────────────
const SEQUENCES = {
  'a steady reply': [{ time: '13ms' }, { time: '14ms' }, { time: '13ms' }],
  'microseconds': [{ time: '783us' }, { time: '1500us' }, { time: '1us' }],
  'a COMPOUND duration keeps only its first unit': [
    { time: '1ms438us' }, { time: '2ms999us' }, { 'min-rtt': '783us', 'max-rtt': '1ms438us', time: '1ms' },
  ],
  'no unit at all': [{ time: '5' }, { time: '0' }, { time: '0.5' }],
  'a timeout among replies': [
    { time: '10ms' }, { status: 'timeout' }, { time: '10ms' }, { time: '10ms' },
  ],
  'ECHO REPLY is not `replied` — it counts as LOST': [
    { time: '1ms', status: 'echo reply' }, { time: '1ms' }, { time: '3ms', status: 'echo reply' },
  ],
  'an explicit replied status': [
    { time: '9ms', status: 'replied' }, { time: '9ms', status: 'replied' },
  ],
  'other statuses': [
    { status: 'host unreachable' }, { status: 'ttl exceeded' }, { status: 'packet too large' },
  ],
  'the rolling window fills and slides': [
    ...Array.from({ length: 9 }, () => ({ time: '5ms' })),
    ...Array.from({ length: 6 }, () => ({ status: 'timeout' })),
    ...Array.from({ length: 6 }, () => ({ time: '5ms' })),
  ],
  'all lost': Array.from({ length: 12 }, () => ({ status: 'timeout' })),
  'min and max ride along': [
    { time: '10ms', 'min-rtt': '9ms', 'max-rtt': '11ms' },
    { time: '12ms', 'min-rtt': '9ms', 'max-rtt': '12ms' },
    { time: '12ms', 'min-rtt': '783us', 'max-rtt': '1ms438us' },
  ],
  'response-time instead of time': [
    { 'response-time': '7ms' }, { 'response-time': '8ms' },
  ],
  'time wins over response-time when both are present': [
    { time: '1ms', 'response-time': '99ms' },
  ],
  'an identical result does not re-emit': [
    { time: '10ms' }, { time: '10ms' }, { time: '10ms' }, { time: '11ms' },
  ],
  'an unparseable duration': [{ time: 'abc' }, { time: '' }, { time: 'ms' }],
  'the history caps at 60': Array.from({ length: 65 }, (_, i) => ({ time: (i % 7) + 'ms' })),
};

const cases = [];
for (const [name, packets] of Object.entries(SEQUENCES)) {
  const { c, emitted } = makeCollector('198.51.100.1');
  const steps = [];
  for (const pkt of packets) {
    const before = emitted.length;
    c._processPacket(pkt);
    const last = c.lastPayload;
    steps.push({
      packet: pkt,
      rtt: last.rtt === undefined ? null : last.rtt,
      loss: last.loss === undefined ? null : last.loss,
      minRtt: last.minRtt === undefined ? null : last.minRtt,
      maxRtt: last.maxRtt === undefined ? null : last.maxRtt,
      emitted: emitted.length > before,
    });
  }
  cases.push({
    name, packets, steps,
    historyLen: c.history.toArray().length,
    // The rtt/loss series the chart draws, which is what a viewer sees.
    history: c.history.toArray().map((p) => ({ rtt: p.rtt, loss: p.loss })),
  });
}

// ── parseRtt on its own, over values the docs show ─────────────────────────
const rttValues = [
  '', '0', '0ms', '1ms', '13ms', '14ms', '783us', '1us', '1000us', '1500us',
  '1ms438us', '2ms999us', '0.5ms', '.5ms', '5', '0.5', 'abc', 'ms', 'us',
  '12', '1m', '1s', '100ms200us', '999999us', '1ms438', '  7ms',
];
const { c: probe } = makeCollector('x');
const parsed = rttValues.map((v) => ({ in: v, out: probe._parseRtt(v) }));

const body = JSON.stringify({
  note: 'GENERATED by tools/ping-cases.js from the LIVE src/collectors/ping.js. Do not edit.',
  lossWindow: 10,
  maxHistory: 60,
  parseRtt: parsed,
  cases,
}, null, 2) + '\n';

// Believability: the corpus must actually distinguish the cases it names.
{
  const echo = cases.find((c) => c.name.startsWith('ECHO REPLY'));
  assert.equal(echo.steps[0].loss, 100,
    'the first `echo reply` did not count as lost — the live rule has changed, and the ' +
    'port reproduces it deliberately');
  const comp = cases.find((c) => c.name.startsWith('a COMPOUND'));
  assert.equal(comp.steps[0].rtt, 1,
    '1ms438us parsed as ' + comp.steps[0].rtt + ', not 1 — the first-unit-only rule has changed');
  const us = cases.find((c) => c.name === 'microseconds');
  assert.equal(us.steps[0].rtt, 0.783, '783us parsed as ' + us.steps[0].rtt);
  const same = cases.find((c) => c.name.startsWith('an identical result'));
  assert.deepEqual(same.steps.map((s) => s.emitted), [true, false, false, true],
    'the emit fingerprint is not suppressing repeats: ' + JSON.stringify(same.steps.map((s) => s.emitted)));
  assert.equal(cases.find((c) => c.name === 'the history caps at 60').historyLen, 60);
}

if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== body) {
    console.error('internal/collect/testdata/ping-cases.json is stale — run: node tools/ping-cases.js');
    process.exit(1);
  }
  console.log('ping-cases: up to date (%d sequences, %d parseRtt values)', cases.length, parsed.length);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log('ping-cases: wrote %d sequences and %d parseRtt values', cases.length, parsed.length);
}
