'use strict';
/**
 * `sanitizeErr`, run against the LIVE implementation.
 *
 * This is a redaction function, so the corpus is built out of the things it must
 * redact and — just as important — the near-misses it must NOT mangle into
 * uselessness. A message that has been over-redacted tells an operator nothing;
 * one that has been under-redacted tells everyone the router's address.
 *
 * The live function is INLINE in src/index.js rather than exported, so it is
 * sliced and run. Its four substitutions are order-dependent and the order is
 * captured by running it rather than by reasoning about it.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/sanitize-cases.js [--check]
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const src = fs.readFileSync(path.join(LIVE, 'src', 'index.js'), 'utf8');
const OUT = path.join(ROOT, 'testdata', 'sanitize-cases.json');

const i = src.indexOf('function sanitizeErr(e) {');
if (i === -1) throw new Error('cannot find sanitizeErr in src/index.js');
const j = src.indexOf('\n}', i);
const fnSrc = src.slice(i, j + 2);
if (!fnSrc.includes('[addr]') || !fnSrc.includes('[token]')) {
  throw new Error('sanitizeErr no longer has the substitutions this corpus was built for');
}
const ctx = { String };
vm.createContext(ctx);
vm.runInContext(fnSrc, ctx);

const CASES = [
  // The one that started this: a Go dial failure names host and port.
  'dial tcp 10.0.0.2:8729: connect: connection refused',
  'dial tcp 192.168.88.1:8728: i/o timeout',
  'dial tcp 198.51.100.7:8729: connect: no route to host',
  // Addresses in other shapes.
  '10.0.0.2',
  '10.0.0.2:8729',
  'from 10.0.0.2 to 10.0.0.3',
  '999.999.999.999 is not an address but is still redacted',
  '1.2.3.4.5',
  'version 7.24.1 is not an address',
  '7.24 is not an address either',
  // Paths, and the fact that they swallow a URL's host.
  '/data/routers.json is unreadable',
  'https://10.0.0.2:8729/rest/interface failed',
  'open /etc/mikrodash/secret: permission denied',
  'C:\\\\Users\\\\op\\\\data is not a unix path',
  'a / on its own',
  'a /x is one character and stays',
  'a /xy is two and goes',
  // Credentials that reach an error message through a provider.
  'SMTP auth failed for operator@example.com',
  'telegram: REDACTED-ROTATED-TOKEN rejected',
  'both operator@example.com and 10.0.0.2 in one line',
  // Empty, whitespace and unicode.
  '',
  '   ',
  'no secrets here at all',
  'ünïcøde error with 10.0.0.2 inside',
  // The 200-unit limit, in three flavours: plain, astral, and just under.
  'x'.repeat(199),
  'x'.repeat(200),
  'x'.repeat(201),
  'x'.repeat(300) + ' 10.0.0.2',
  '😀'.repeat(120),
  'e'.repeat(190) + '😀😀😀😀😀😀😀😀',
  // Redaction that lengthens the string past the limit.
  ('10.0.0.2 ').repeat(40),
];

const cases = CASES.map((input) => ({ input, want: ctx.sanitizeErr(input) }));
// A null error answers null in the original; Go has no null string, so the Go
// side maps "" to "". Recorded so the difference is deliberate and visible.
const body = JSON.stringify({
  note: 'Generated by tools/sanitize-cases.js from the LIVE src/index.js sanitizeErr. Do not edit.',
  nullNote: 'sanitizeErr(null) is null in the original; Go has no nullable string and answers "" ' +
    'for "". The only caller passes err.Error(), which is never null.',
  cases,
}, null, 2) + '\n';

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (cur !== body) {
    console.error('testdata/sanitize-cases.json is stale — run: node tools/sanitize-cases.js');
    process.exit(1);
  }
  console.log('sanitize cases up to date (' + cases.length + ' messages)');
} else {
  fs.writeFileSync(OUT, body);
  const changed = cases.filter((c) => c.input !== c.want).length;
  console.log('wrote testdata/sanitize-cases.json — ' + cases.length + ' messages, ' +
    changed + ' redacted');
}
