'use strict';
/**
 * `switchRouter` — what changing the GLOBAL active router actually does — as a
 * corpus generated by RUNNING the live implementation.
 *
 * ---- WHY THIS IS NEEDED BEFORE THE ROUTE CAN BE PORTED --------------------
 *
 * `POST /api/routers/:id/activate` is the last piece of the first-run router
 * overlay, and it is not a thin route: it answers `{ok:true, switching:true}`
 * BEFORE the work happens, and everything an operator actually sees arrives over
 * the socket afterwards. So the interesting behaviour is entirely inside
 * `switchRouter`, and none of it is visible in the response.
 *
 * The route also WRITES settings.json, which Node caches and would revert
 * (PORT-QUEUE.md blocker 3) — so the wiring waits for cutover and the decisions
 * are pinned now, the same order the overlay's own gate used.
 *
 * ---- SLICED AND STUBBED, AND THE STUBS ARE THE RECORDER -------------------
 *
 * `switchRouter` closes over twelve module-level names — the router store, the
 * settings, the socket server, the session pool, three session helpers, the
 * alerter and two flags. Every one is the layer BELOW the decision, so every one
 * is stubbed, and what the stubs record IS the corpus: the ORDERED operations.
 *
 * Order is the point. This function tears down a session, saves a setting,
 * relocates sockets and starts a new one, and the live comments are explicit
 * that several of those orderings are load-bearing:
 *
 *   - the OLD active id is read BEFORE `Settings.save`, or the teardown targets
 *     the router just switched to;
 *   - only sockets watching the OUTGOING router move, because "a global emit
 *     would wipe charts/logs in every other user's browser";
 *   - the synthetic `ros:status` is `true` ONLY — "a synthetic false would be
 *     the client's SECOND false and would dismiss the switching overlay while
 *     the new router is still connecting".
 *
 * A corpus recording only the final state would see none of those.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/switchrouter-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/switchrouter-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const OUT = path.join(ROOT, 'testdata', 'switchrouter-cases.json');

// ---- Slice the function out of index.js ------------------------------------
const lines = fs.readFileSync(path.join(LIVE, 'src', 'index.js'), 'utf8').split('\n');
const start = lines.findIndex((l) => l.startsWith('async function switchRouter('));
if (start < 0) throw new Error('anchor lost: `async function switchRouter(` at column 0');
const end = lines.findIndex((l, i) => i > start && l === '}');
if (end < 0) throw new Error('anchor lost: the closing brace of switchRouter');
const slice = lines.slice(start, end + 1).join('\n');

// The decisions this corpus exists to pin. A slice that lost one would still
// evaluate and would agree with a Go function that did nothing.
for (const need of [
  'Settings.save', 'teardownSession', 'ensureRouterSession', 'dropEvaluator',
  'router:switching', 'ros:status', 'rosConnected', 'startupReady',
]) {
  if (!slice.includes(need)) throw new Error(`slice does not mention ${need} - the anchors drifted`);
}
// THE ORDER THAT MATTERS MOST, checked at the SOURCE as well as in the outputs:
// the old id must be read before the save, or the teardown targets the router
// just switched to. Nothing in a recorded operation list shows a read.
if (slice.indexOf('const oldActiveId') > slice.indexOf('Settings.save')) {
  throw new Error('Settings.save now runs BEFORE oldActiveId is read; the teardown would '
    + 'target the router just switched to');
}

/** One run, with every dependency stubbed and recording. */
function runCase(c) {
  const ops = [];
  const sockets = (c.sockets || []).map((s) => ({
    id: s.id,
    routerId: s.routerId,
    rooms: new Set(s.rooms || []),
    leave(room) { this.rooms.delete(room); ops.push({ op: 'leave', socket: this.id, room }); },
    join(room) { this.rooms.add(room); ops.push({ op: 'join', socket: this.id, room }); },
  }));

  const emitter = (target) => ({
    emit: (event, payload) => ops.push({ op: 'emit', to: target, event, payload }),
  });

  const sandbox = {
    console: { log: () => {}, error: (...a) => ops.push({ op: 'log', text: a.map(String).join(' ') }) },
    Routers: { getById: (id) => (c.routers || {})[id] || null },
    Settings: {
      load: () => ({ activeRouterId: c.activeRouterId === undefined ? null : c.activeRouterId }),
      save: (patch) => ops.push({ op: 'settings.save', patch }),
    },
    io: {
      to: (room) => emitter(room),
      emit: (event, payload) => ops.push({ op: 'emit', to: '*', event, payload }),
      sockets: { sockets: new Map(sockets.map((s) => [s.id, s])) },
    },
    _routerSessions: new Map(Object.entries(c.pool || {}).map(([k, v]) => [k, {
      ...v, session: v.session === undefined ? {} : v.session, __id: k,
    }])),
    ensureRouterSession: (id) => {
      ops.push({ op: 'ensureRouterSession', routerId: id });
      return c.newEntry === undefined ? null : c.newEntry;
    },
    teardownSession: async (_s, entry) => { ops.push({ op: 'teardown', routerId: entry.__id }); },
    broadcastRosStatus: (connected, reason) =>
      ops.push({ op: 'broadcastRosStatus', connected, reason }),
    alerter: { dropEvaluator: (id) => ops.push({ op: 'dropEvaluator', routerId: id }) },
    _replayToRoomSockets: () => ops.push({ op: 'replay' }),
    _noRouterMode: true,
    _switching: !!c.switching,
    clearTimeout: () => ops.push({ op: 'clearTimeout' }),
    setTimeout,
  };

  const fn = vm.runInNewContext(`(${slice})`, sandbox, { filename: 'index.js#switchRouter' });
  return fn(c.newRouterId).then((result) => ({ result, ops, switching: sandbox._switching }));
}

const R = (id, label) => ({ id, label, host: '198.51.100.9' });
const CASES = [
  {
    why: 'a switch with NO previous active router - the first-run overlay\'s case',
    newRouterId: 'r2', activeRouterId: null,
    routers: { r2: R('r2', 'Two') }, pool: {}, newEntry: { rosConnected: false },
    sockets: [],
  },
  {
    // ADDED after a Go test disagreed with a first draft of the port. With no
    // outgoing router there is nobody following one, and the question is what
    // happens to a socket that is itself following NOTHING — `undefined ===
    // null` in the live predicate. Asking the implementation rather than
    // reasoning about JavaScript equality.
    why: 'NO previous active router, and a socket following nothing',
    newRouterId: 'r2', activeRouterId: null,
    routers: { r2: R('r2', 'Two') }, pool: {}, newEntry: { rosConnected: false },
    sockets: [{ id: 'unattached', routerId: undefined, rooms: ['lobby'] }],
  },
  {
    why: 'a switch away from an active router that has a pooled session',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') },
    pool: { r1: { rosConnected: true, idleTimer: 1 } },
    newEntry: { rosConnected: false },
    sockets: [{ id: 's1', routerId: 'r1', rooms: ['router-r1', 'router-r1:wifi'] }],
  },
  {
    why: 'a socket watching a DIFFERENT router is left alone',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') },
    pool: { r1: { rosConnected: true } }, newEntry: { rosConnected: false },
    sockets: [
      { id: 'following', routerId: 'r1', rooms: ['router-r1'] },
      { id: 'pinned-elsewhere', routerId: 'r3', rooms: ['router-r3'] },
    ],
  },
  {
    why: 'a socket already on the new router is not moved to it again',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') },
    pool: { r1: {} }, newEntry: { rosConnected: false },
    sockets: [{ id: 'already', routerId: 'r2', rooms: ['router-r2'] }],
  },
  {
    why: 'ROOMS ARE LEFT BY PREFIX, so a sub-room like router-r1:wifi goes too',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') },
    pool: { r1: {} }, newEntry: { rosConnected: false },
    sockets: [{ id: 's1', routerId: 'r1', rooms: ['router-r1', 'router-r1:wifi', 'lobby'] }],
  },
  {
    why: 'the new session is ALREADY connected, so a synthetic ros:status true is sent (#118)',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') }, pool: { r1: {} },
    newEntry: { rosConnected: true, startupReady: true, session: {} },
    sockets: [],
  },
  {
    why: 'already connected but NOT startupReady - the status is sent, the replay is not',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') }, pool: { r1: {} },
    newEntry: { rosConnected: true, startupReady: false, session: {} },
    sockets: [],
  },
  {
    why: 'a NOT-yet-connected new session sends no synthetic status at all',
    newRouterId: 'r2', activeRouterId: 'r1',
    routers: { r2: R('r2', 'Two') }, pool: { r1: {} },
    newEntry: { rosConnected: false, startupReady: true, session: {} },
    sockets: [],
  },
  {
    // ADDED after a mutation swapping the two refusals survived: no case had
    // BOTH conditions, so their ORDER was unobservable. The live code checks the
    // flag first, so a busy switch reports that even when the id is also bad.
    why: 'REFUSAL: both at once - a busy switch reports the flag, not the bad id',
    newRouterId: 'nope', activeRouterId: 'r1', switching: true,
    routers: {}, pool: {}, sockets: [],
  },
  {
    // ADDED after a mutation dropping the `!== newRouterId` clause survived. It
    // is unreachable unless the new router IS the old one — the ROUTE
    // short-circuits that with `alreadyActive`, but switchRouter has two other
    // callers and no such guard of its own.
    why: 'switching to the router that is ALREADY active',
    newRouterId: 'r1', activeRouterId: 'r1',
    routers: { r1: R('r1', 'One') }, pool: { r1: { rosConnected: true } },
    newEntry: { rosConnected: false },
    sockets: [{ id: 'onIt', routerId: 'r1', rooms: ['router-r1', 'router-r1:wifi'] }],
  },
  {
    why: 'REFUSAL: an unknown router id',
    newRouterId: 'nope', activeRouterId: 'r1', routers: {}, pool: {}, sockets: [],
  },
  {
    why: 'REFUSAL: a switch is already in progress',
    newRouterId: 'r2', activeRouterId: 'r1', switching: true,
    routers: { r2: R('r2', 'Two') }, pool: {}, sockets: [],
  },
];

Promise.all(CASES.map((c) => runCase(c).then((r) => ({
  why: c.why,
  input: {
    newRouterId: c.newRouterId,
    activeRouterId: c.activeRouterId === undefined ? null : c.activeRouterId,
    // The LABEL matters: it appears in the router:switching payload and in the
    // broadcastRosStatus reason, so a consumer needs it and a bare id list would
    // make those two steps unreproducible.
    knownRouters: Object.fromEntries(
      Object.entries(c.routers || {}).map(([id, r]) => [id, r.label])),
    // And the pool's ENTRIES, not just its keys: `idleTimer` decides whether a
    // clearTimeout precedes the teardown.
    pooled: Object.fromEntries(
      Object.entries(c.pool || {}).map(([id, v]) => [id, { hasIdleTimer: !!v.idleTimer }])),
    newEntry: c.newEntry === undefined ? null : c.newEntry,
    switching: !!c.switching,
    sockets: (c.sockets || []).map((s) => ({ id: s.id, routerId: s.routerId, rooms: s.rooms || [] })),
  },
  result: r.result,
  ops: r.ops,
  // THE FLAG MUST BE RELEASED whatever happened. The live code uses a `finally`;
  // a port releasing it only on the success path would refuse every subsequent
  // switch after one failure, and nothing about the first failure would look
  // wrong.
  switchingAfter: r.switching,
})))).then((out) => {
  // ---- Believability -------------------------------------------------------
  const byWhy = Object.fromEntries(out.map((c) => [c.why, c]));
  const need = (k) => {
    if (!byWhy[k]) throw new Error(`a believability check names a case that is gone: ${k}`);
    return byWhy[k];
  };
  const opsOf = (c, op) => c.ops.filter((o) => o.op === op);

  // THE REFUSALS return, and touch nothing.
  for (const k of ['REFUSAL: an unknown router id', 'REFUSAL: a switch is already in progress']) {
    const c = need(k);
    if (c.result.ok !== false || !c.result.error) throw new Error(`${k}: expected {ok:false,error}`);
    if (opsOf(c, 'settings.save').length) throw new Error(`${k}: it saved a setting anyway`);
    if (opsOf(c, 'teardown').length) throw new Error(`${k}: it tore a session down anyway`);
  }
  // THE FLAG IS RELEASED BY EVERY PATH THAT TOOK IT, and by no other.
  //
  // The distinction is the whole of the guard and I had it backwards first time.
  // The already-in-progress refusal returns BEFORE the `try`, so it must leave
  // the flag SET — the flag belongs to the switch still running, and clearing it
  // would let a second one start on top of the first, which is precisely what it
  // exists to prevent. Every other path goes through the `finally` and must
  // clear it, or one failure refuses every switch afterwards and nothing about
  // that first failure looks wrong.
  // Keyed on the ERROR, not on a case name. Keying on the name meant a SECOND
  // already-in-progress case — one that also has a bad id, added to pin the
  // order of the two refusals — was checked as if it should have released the
  // flag. The condition is what decides this, so the condition is what is asked.
  const busy = out.filter((c) => c.result.error === 'Switch already in progress');
  if (!busy.length) throw new Error('no case exercises the in-progress refusal');
  for (const c of busy) {
    if (!c.switchingAfter) {
      throw new Error(`${c.why}: the already-in-progress refusal CLEARED the flag. It returns `
        + 'before the try/finally precisely so it cannot: the flag belongs to the switch still '
        + 'running.');
    }
  }
  for (const c of out) {
    if (busy.includes(c)) continue;
    if (c.switchingAfter) {
      throw new Error(`${c.why}: the _switching flag was left set; every later switch would be `
        + 'refused and nothing about this one would look wrong');
    }
  }
  // THE SAVE happens exactly once on a real switch, and names the new id.
  const real = out.filter((c) => c.result.ok);
  if (real.length < 6) throw new Error(`only ${real.length} cases switched`);
  for (const c of real) {
    const saves = opsOf(c, 'settings.save');
    if (saves.length !== 1) throw new Error(`${c.why}: ${saves.length} saves, want 1`);
    if (saves[0].patch.activeRouterId !== c.input.newRouterId) {
      throw new Error(`${c.why}: saved ${JSON.stringify(saves[0].patch)}`);
    }
  }
  // THE SOCKET RULE, in both directions.
  const other = need('a socket watching a DIFFERENT router is left alone');
  if (other.ops.some((o) => o.op === 'join' && o.socket === 'pinned-elsewhere')) {
    throw new Error('a socket pinned to another router was relocated');
  }
  if (!other.ops.some((o) => o.op === 'join' && o.socket === 'following')) {
    throw new Error('a socket following the outgoing router was NOT relocated');
  }
  const already = need('a socket already on the new router is not moved to it again');
  if (already.ops.some((o) => o.op === 'join')) {
    throw new Error('a socket already on the new router was moved again');
  }
  // THE PREFIX RULE: the sub-room goes, the unrelated room stays.
  const prefix = need('ROOMS ARE LEFT BY PREFIX, so a sub-room like router-r1:wifi goes too');
  const left = opsOf(prefix, 'leave').map((o) => o.room);
  if (!left.includes('router-r1') || !left.includes('router-r1:wifi')) {
    throw new Error('the prefix rule stopped catching sub-rooms: ' + JSON.stringify(left));
  }
  if (left.includes('lobby')) throw new Error('an unrelated room was left');
  // THE SYNTHETIC STATUS: true only, and only when already connected.
  const pooled = need('the new session is ALREADY connected, so a synthetic ros:status true is sent (#118)');
  const synth = pooled.ops.filter((o) => o.op === 'emit' && o.event === 'ros:status');
  if (synth.length !== 1 || synth[0].payload.connected !== true) {
    throw new Error('the #118 synthetic status is gone: ' + JSON.stringify(synth));
  }
  if (!opsOf(pooled, 'replay').length) throw new Error('the replay is gone');
  const notReady = need('already connected but NOT startupReady - the status is sent, the replay is not');
  if (opsOf(notReady, 'replay').length) {
    throw new Error('the replay ran without startupReady; every socket pays a duplicate fetch');
  }
  const cold = need('a NOT-yet-connected new session sends no synthetic status at all');
  if (cold.ops.some((o) => o.op === 'emit' && o.event === 'ros:status')) {
    throw new Error('a synthetic status was sent for a session that is not connected');
  }
  // No case may emit a synthetic FALSE anywhere.
  for (const c of out) {
    for (const o of c.ops) {
      if (o.op === 'emit' && o.event === 'ros:status' && o.payload.connected === false) {
        throw new Error(`${c.why}: a synthetic ros:status FALSE was emitted. It would be the `
          + "client's second false and would dismiss the switching overlay early.");
      }
    }
  }
  // No credential may appear: this function reads a router RECORD, which has one.
  const blob = JSON.stringify(out).toLowerCase();
  for (const bad of ['password', 'passwordhash', 'salt', 'secret']) {
    if (blob.includes(bad)) throw new Error(`corpus contains ${bad}`);
  }

  const json = JSON.stringify({ generated_from: 'src/index.js switchRouter', cases: out }, null, 2) + '\n';
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (have !== json) {
      console.error('STALE: testdata/switchrouter-cases.json - re-run tools/switchrouter-cases.js');
      process.exit(1);
    }
    console.log(`switchrouter-cases: up to date (${out.length} cases)`);
  } else {
    fs.writeFileSync(OUT, json);
    console.log(`wrote ${OUT} (${out.length} cases, ${real.length} real switches)`);
  }
}).catch((e) => {
  console.error(e.message);
  process.exit(1);
});
