'use strict';
/**
 * `Rbac.syncUserGrants` — WHICH GRANTS a user gets — as a corpus generated by
 * RUNNING the live implementation.
 *
 * ---- WHY THIS ONE MATTERS MORE THAN ITS SIZE SUGGESTS ----------------------
 *
 * It is twenty-five lines and it decides whether a person can use the
 * application at all. The live route that mints the first administrator calls
 * it, with this comment: "Without this the very first administrator of a fresh
 * install holds no grants, and every guard refuses them — locked out of their
 * own instance the moment setup completes."
 *
 * Getting it wrong in the other direction is worse and quieter: an over-broad
 * grant is a person who can see routers nobody gave them.
 *
 * ---- THE INVERSION IS THE TRAP --------------------------------------------
 *
 * `allowedRouterIds: []` means UNRESTRICTED, not "no routers". An empty list
 * produces ONE GLOBAL grant; a non-empty one produces a router-scoped grant per
 * id. Read quickly, the code says the opposite of what it does, and a port that
 * "fixed" it would lock out every unrestricted user on the first run after
 * cutover — including, on a fresh install, the only administrator.
 *
 * Three separate inputs collapse into that empty case and they do not look
 * alike: `[]`, a NON-ARRAY (null, undefined, a string), and a list whose entries
 * are all falsy, because `.filter(Boolean)` runs before the length test. So
 * `allowedRouterIds: ['']` is UNRESTRICTED. All of them are in the corpus.
 *
 * ---- AND IT IS A REPLACE, NOT AN ADD --------------------------------------
 *
 * `deleteGrantsForPrincipal` runs first, unconditionally — before the branch
 * that decides what to write. A user whose every id is unknown therefore ends
 * with NO grants at all, which is a different outcome from the empty case and
 * the only way this function can lock somebody out. The corpus records the
 * delete as an operation rather than assuming it.
 *
 * ---- HOW IT IS LIFTED ------------------------------------------------------
 *
 * `src/rbac.js` requires a database and a router store at module load, so it
 * cannot simply be required. The function is SLICED out by content anchors and
 * evaluated in a `vm` with `db`, `Routers`, `bump` and `console` stubbed — the
 * layer BELOW the decision, and nothing else. What the stubs record IS the
 * corpus: the ordered operations, not a summary of them.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/syncgrants-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/syncgrants-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const OUT = path.join(ROOT, 'testdata', 'syncgrants-cases.json');

// ---- Slice the function out of rbac.js -------------------------------------
const src = fs.readFileSync(path.join(LIVE, 'src', 'rbac.js'), 'utf8');
const lines = src.split('\n');
const start = lines.findIndex((l) => l.startsWith('function syncUserGrants('));
if (start < 0) throw new Error('anchor lost: `function syncUserGrants(` at column 0 in rbac.js');
const end = lines.findIndex((l, i) => i > start && l === '}');
if (end < 0) throw new Error('anchor lost: the closing brace of syncUserGrants');
const slice = lines.slice(start, end + 1).join('\n');

// The three effects the decision is made OF. A slice that lost one would still
// evaluate and would agree with a Go function that never wrote anything.
for (const need of ['deleteGrantsForPrincipal', 'upsertGrant', 'liveRouterIds']) {
  if (!slice.includes(need)) {
    throw new Error(`slice does not mention ${need} - the anchors drifted`);
  }
}
// The inversion, checked at the SOURCE as well as in the outputs. If upstream
// ever makes an empty list mean "no access", every output below flips and the
// port must be rewritten rather than regenerated — so it fails loudly here,
// naming the thing to go and read.
if (!/if\s*\(!ids\.length\)/.test(slice)) {
  throw new Error('the empty-list branch is no longer `if (!ids.length)`. An empty '
    + 'allowedRouterIds meant UNRESTRICTED; if that changed, this is not a regeneration, '
    + 'it is a re-port - read internal/rbac/syncgrants.go before touching this file.');
}

// The stubs ARE the recorder. `Routers` and `db` are the layer below the
// decision; `bump` and `console` are noise the decision does not depend on, and
// the bump is recorded anyway because forgetting it is how a cache goes stale.
function runCase(user, routers) {
  const ops = [];
  const sandbox = {
    Routers: { loadAll: () => routers },
    db: {
      deleteGrantsForPrincipal: (t, id) => ops.push({ op: 'delete', principalType: t, principalId: id }),
      upsertGrant: (g) => ops.push({ op: 'upsert', ...g }),
    },
    bump: () => ops.push({ op: 'bump' }),
    console: { warn: (...a) => ops.push({ op: 'warn', text: a.map(String).join(' ') }) },
  };
  const fn = vm.runInNewContext(`(${slice})`, sandbox, { filename: 'rbac.js#syncUserGrants' });
  const made = fn(user);
  return { made, ops };
}

const R = (id) => ({ id });
const FLEET = [R('r1'), R('r2'), R('r3')];

const CASES = [
  // ---- The inversion, every way of reaching it -----------------------------
  ['an empty list is UNRESTRICTED, not no access',
    { id: 'u1', username: 'ann', role: 'admin', allowedRouterIds: [] }, FLEET],
  ['an ABSENT list is unrestricted too - the array check fails, not the length',
    { id: 'u2', username: 'bob', role: 'admin' }, FLEET],
  ['null is unrestricted',
    { id: 'u3', username: 'cy', role: 'viewer', allowedRouterIds: null }, FLEET],
  ['a STRING is not an array, so it is unrestricted - not one grant per character',
    { id: 'u4', username: 'di', role: 'viewer', allowedRouterIds: 'r1' }, FLEET],
  ['a list of only falsy ids is unrestricted: filter(Boolean) runs BEFORE the length test',
    { id: 'u5', username: 'eve', role: 'admin', allowedRouterIds: ['', null, 0] }, FLEET],

  // ---- Router-scoped grants ------------------------------------------------
  ['one known router is one router-scoped grant',
    { id: 'u6', username: 'fay', role: 'operator', allowedRouterIds: ['r1'] }, FLEET],
  ['several known routers are one grant each, in the order given',
    { id: 'u7', username: 'gus', role: 'viewer', allowedRouterIds: ['r3', 'r1'] }, FLEET],
  ['a falsy entry among real ones is dropped without dropping the others',
    { id: 'u8', username: 'hal', role: 'admin', allowedRouterIds: ['r1', '', 'r2'] }, FLEET],
  ['a numeric id is stringified for BOTH the lookup and the scope',
    { id: 'u9', username: 'ivy', role: 'viewer', allowedRouterIds: [1] },
    [R('1'), R('r1')]],
  ['a DUPLICATE id is not de-duplicated - the upsert absorbs it',
    { id: 'u10', username: 'jo', role: 'admin', allowedRouterIds: ['r1', 'r1'] }, FLEET],

  // ---- The lockout case ----------------------------------------------------
  ['an unknown router is dropped with a warning',
    { id: 'u11', username: 'kim', role: 'admin', allowedRouterIds: ['r1', 'gone'] }, FLEET],
  ['EVERY id unknown leaves the user with NO grants - the delete already ran',
    { id: 'u12', username: 'lee', role: 'admin', allowedRouterIds: ['gone', 'also-gone'] }, FLEET],
  ['an empty fleet makes every id unknown',
    { id: 'u13', username: 'moe', role: 'admin', allowedRouterIds: ['r1'] }, []],
  ['an empty fleet does NOT affect the unrestricted case',
    { id: 'u14', username: 'ned', role: 'admin', allowedRouterIds: [] }, []],

  // ---- The role ladder -----------------------------------------------------
  ['admin stays admin',
    { id: 'u15', username: 'ola', role: 'admin', allowedRouterIds: [] }, FLEET],
  ['operator stays operator',
    { id: 'u16', username: 'pat', role: 'operator', allowedRouterIds: [] }, FLEET],
  ['viewer stays viewer',
    { id: 'u17', username: 'quy', role: 'viewer', allowedRouterIds: [] }, FLEET],
  ['an UNKNOWN role becomes viewer, not admin - least privilege',
    { id: 'u18', username: 'rex', role: 'superuser', allowedRouterIds: [] }, FLEET],
  ['an ABSENT role becomes viewer',
    { id: 'u19', username: 'sam', allowedRouterIds: [] }, FLEET],
  ['role is matched EXACTLY - "Admin" is not admin',
    { id: 'u20', username: 'tia', role: 'Admin', allowedRouterIds: [] }, FLEET],
  ['and the role applies to router-scoped grants too, not only global ones',
    { id: 'u21', username: 'uma', role: 'nonsense', allowedRouterIds: ['r1'] }, FLEET],

  // ---- The refusals --------------------------------------------------------
  ['a user with no id does NOTHING AT ALL - not even the delete',
    { username: 'vic', role: 'admin', allowedRouterIds: [] }, FLEET],
  ['an empty id is falsy, so the same',
    { id: '', username: 'wes', role: 'admin' }, FLEET],
];

const out = CASES.map(([why, user, routers]) => {
  const { made, ops } = runCase(user, routers);
  return {
    why,
    user: {
      id: user.id === undefined ? null : user.id,
      username: user.username === undefined ? null : user.username,
      role: user.role === undefined ? null : user.role,
      // Recorded as it was PASSED, including the non-array shapes, because the
      // coercion is the rule rather than a detail of the input format.
      allowedRouterIds: user.allowedRouterIds === undefined ? null : user.allowedRouterIds,
      allowedRouterIdsAbsent: !('allowedRouterIds' in user),
    },
    routerIds: routers.map((r) => r.id),
    made,
    // The ORDERED operations. A port writing the right grants in the wrong order
    // — upserting before deleting — destroys what it just wrote, and a corpus
    // recording only the final set would not see it.
    ops,
  };
});

// ---- Believability ---------------------------------------------------------
// Every assertion is about what the LIVE side did. The failure guarded against
// is silent: a slice that threw on every case, or stubs that recorded nothing,
// would agree with an empty Go function.
const byWhy = Object.fromEntries(out.map((c) => [c.why, c]));
const need = (k) => {
  if (!byWhy[k]) throw new Error(`a believability check names a case that is gone: ${k}`);
  return byWhy[k];
};
const upserts = (c) => c.ops.filter((o) => o.op === 'upsert');

// THE INVERSION, in the outputs as well as the source. Every spelling of "empty"
// must produce exactly one GLOBAL grant.
for (const k of ['an empty list is UNRESTRICTED, not no access',
  'an ABSENT list is unrestricted too - the array check fails, not the length',
  'null is unrestricted',
  'a STRING is not an array, so it is unrestricted - not one grant per character',
  'a list of only falsy ids is unrestricted: filter(Boolean) runs BEFORE the length test']) {
  const g = upserts(need(k));
  if (g.length !== 1 || g[0].scopeType !== 'global') {
    throw new Error(`${k}: expected one global grant, got ${JSON.stringify(g)}. If upstream `
      + 'inverted this, the port must be re-read rather than regenerated.');
  }
}
// THE LOCKOUT, which is the outcome the empty case exists not to be confused
// with.
const lockout = need('EVERY id unknown leaves the user with NO grants - the delete already ran');
if (upserts(lockout).length !== 0) {
  throw new Error('an all-unknown list stopped producing zero grants');
}
if (!lockout.ops.some((o) => o.op === 'delete')) {
  throw new Error('the delete no longer runs before the branch, so this is not a replace');
}
// LEAST PRIVILEGE. An unknown role must not become admin, and the three ways of
// being unknown are checked separately.
for (const k of ['an UNKNOWN role becomes viewer, not admin - least privilege',
  'an ABSENT role becomes viewer', 'role is matched EXACTLY - "Admin" is not admin']) {
  const g = upserts(need(k));
  if (!g.length || g[0].role !== 'viewer') {
    throw new Error(`${k}: role came out as ${JSON.stringify(g[0] && g[0].role)}, want viewer`);
  }
}
if (upserts(need('admin stays admin'))[0].role !== 'admin') {
  throw new Error('admin no longer maps to admin - the ladder collapsed');
}
if (upserts(need('operator stays operator'))[0].role !== 'operator') {
  throw new Error('operator no longer maps to operator');
}
// THE REFUSAL does nothing at all, delete included. A port that deleted first
// and then checked the id would wipe a real user's grants on a malformed call.
for (const k of ['a user with no id does NOTHING AT ALL - not even the delete',
  'an empty id is falsy, so the same']) {
  if (need(k).ops.length !== 0 || need(k).made !== 0) {
    throw new Error(`${k}: expected no operations, got ${JSON.stringify(need(k).ops)}`);
  }
}
// ORDER. The delete must precede every upsert in every case that has one.
for (const c of out) {
  const d = c.ops.findIndex((o) => o.op === 'delete');
  const u = c.ops.findIndex((o) => o.op === 'upsert');
  if (u >= 0 && (d < 0 || d > u)) {
    throw new Error(`${c.why}: an upsert happens before the delete, which would destroy it`);
  }
}
// Both answers occur, and the corpus is not one shape repeated.
const distinct = new Set(out.map((c) => JSON.stringify(c.ops.map((o) => o.op + ':' + (o.scopeType || '')))));
if (distinct.size < 4) {
  throw new Error(`only ${distinct.size} distinct operation shapes; the corpus proves little`);
}
// No credential may appear. `syncUserGrants` reads no password, so anything
// password-shaped here means the wrong object was passed in.
const blob = JSON.stringify(out).toLowerCase();
for (const bad of ['passwordhash', 'salt', 'password']) {
  if (blob.includes(bad)) throw new Error(`corpus contains ${bad} - it must carry no credential`);
}

const json = JSON.stringify({ generated_from: 'src/rbac.js syncUserGrants', cases: out }, null, 2) + '\n';
if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== json) {
    console.error('STALE: testdata/syncgrants-cases.json - re-run tools/syncgrants-cases.js');
    process.exit(1);
  }
  console.log(`syncgrants-cases: up to date (${out.length} cases)`);
} else {
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${OUT} (${out.length} cases, ${distinct.size} distinct operation shapes)`);
}
