'use strict';
/**
 * The page-nav map and the view presets, from public/app.js.
 *
 * ── `advanced` IS DERIVED, NOT LISTED ──────────────────────────────────────
 *
 * The live source says why: "Derived, so a page added to the nav joins Advanced
 * by existing". Only `home` and `standard` are written out; Advanced is every
 * page that has a toggle. Recording it as a flat list here would freeze it, and
 * the next page added would silently drop out of the preset — so this captures
 * the two explicit lists and the map, and the port derives the third exactly as
 * the original does.
 *
 * PAGE_NAV_MAP is settings-key -> page-key, and the presets name PAGE KEYS. The
 * two vocabularies are easy to confuse: `pageWifi` is the checkbox, `wifi` is
 * what a preset lists.
 *
 *   node tools/view-presets.js            write the tables
 *   node tools/view-presets.js --check    exit 1 if stale
 */

const fs = require('node:fs');
const path = require('node:path');

const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(__dirname, '..', '..', 'MikroDash'));
const OUT = path.join(__dirname, '..', 'testdata', 'view-presets.json');
const src = fs.readFileSync(path.join(LIVE, 'public', 'app.js'), 'utf8');

function slice(decl, close) {
  const i = src.indexOf(decl);
  if (i === -1) throw new Error('cannot find `' + decl + '` in public/app.js');
  const j = src.indexOf(close, i);
  if (j === -1) throw new Error('`' + decl + '` is never closed');
  return src.slice(i, j + close.length);
}

// settings key -> page key
const navBlock = slice('var PAGE_NAV_MAP = {', '\n};');
const navMap = {};
for (const m of navBlock.matchAll(/(\w+)\s*:\s*'([^']+)'/g)) navMap[m[1]] = m[2];
if (Object.keys(navMap).length < 15) {
  throw new Error('PAGE_NAV_MAP yielded only ' + Object.keys(navMap).length +
    ' entries — the literal changed shape');
}

// The two EXPLICIT presets. `advanced` is deliberately not read: it is null in
// the literal and filled at runtime from the map.
const presetBlock = slice('  var VIEW_PRESETS = {', '\n  };');
const presets = {};
for (const name of ['home', 'standard']) {
  const m = presetBlock.match(new RegExp(name + ":\\s*\\[([\\s\\S]*?)\\]"));
  if (!m) throw new Error('cannot find the `' + name + '` preset');
  presets[name] = [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]);
  if (!presets[name].length) throw new Error('the `' + name + '` preset came out empty');
}
if (!/advanced:\s*null/.test(presetBlock)) {
  throw new Error('`advanced` is no longer null in the literal — it may have been ' +
    'written out as a list, in which case the port must stop deriving it');
}

// Every page a preset names must exist in the map, or the preset can never match.
const pageKeys = new Set(Object.values(navMap));
for (const [name, list] of Object.entries(presets)) {
  for (const p of list) {
    if (!pageKeys.has(p)) {
      throw new Error('preset ' + name + ' names the page ' + p + ', which is not in PAGE_NAV_MAP');
    }
  }
}

const keyMatch = src.match(/var VIEW_PRESET_KEY = '([^']+)'/);
if (!keyMatch) throw new Error('cannot find VIEW_PRESET_KEY');

const body = JSON.stringify({
  note: 'Generated by tools/view-presets.js from the LIVE public/app.js. Do not edit. ' +
        '`advanced` is NOT recorded — it is derived from navMap, as the original derives it.',
  storageKey: keyMatch[1],
  navMap,
  presets,
}, null, 2) + '\n';

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (cur !== body) {
    console.error('testdata/view-presets.json is stale — run: node tools/view-presets.js');
    process.exit(1);
  }
  console.log('view presets up to date (' + Object.keys(navMap).length + ' pages)');
} else {
  fs.writeFileSync(OUT, body);
  console.log('wrote ' + path.relative(path.join(__dirname, '..'), OUT) + ' — ' +
              Object.keys(navMap).length + ' pages, home=' + presets.home.length +
              ', standard=' + presets.standard.length + ', advanced derived');
}
