'use strict';
/**
 * The WiFi frequency scan's PURE halves, as a corpus generated by RUNNING
 * `src/wifiScan.js`.
 *
 * That module is, in its own words, "the first deliberately DISRUPTIVE thing
 * MikroDash does" — a frequency scan "will disconnect all connected clients".
 * The runner, the wall-clock stop, the fleet cap and the cooldown all exist
 * because of that, and NONE of them is ported here: they need a router.
 *
 * What is ported is the three exported functions that need nothing: the band
 * arithmetic, the row parser and the trap classifier. They are what turns a
 * scan's output into something a page can draw, and they are wrong in ways a
 * reading does not catch.
 *
 * ---- WHAT THE CASES ARE SHAPED AROUND --------------------------------------
 *
 *   the /5 GRID          5163 MHz is inside the 5GHz band and NOT on the grid,
 *                        so it has no channel — "5163 MHz" is honest, "channel
 *                        32.6" is not.
 *   2484                 Japan's channel 14, off the grid and special-cased.
 *   BAND ORDER           6GHz is tested before 5GHz and uses its own base.
 *   COMPOUND CHANNELS    `/interface/wifi/monitor` reports "2427/ax/Ce", so the
 *                        parser takes the leading integer and keeps the raw.
 *   A ROW THAT WILL NOT  is DROPPED, not rendered as NaN — a bar at x=NaN
 *   PARSE                disappears and looks like a channel never scanned.
 *   TRAP ORDER           "no such command prefix" contains "no such", so the
 *                        unsupported-stack test must come before the
 *                        no-such-interface one or every unsupported stack reads
 *                        as a missing interface.
 *
 *   MIKRODASH_SRC=../MikroDash node tools/wifiscan-cases.js          # write
 *   MIKRODASH_SRC=../MikroDash node tools/wifiscan-cases.js --check  # fail if stale
 */

const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert');

const ROOT = path.join(__dirname, '..');
const LIVE = path.resolve(process.env.MIKRODASH_SRC || path.join(ROOT, '..', 'MikroDash'));
const ws = require(path.join(LIVE, 'src', 'wifiScan.js'));
const { freqToChannel, parseRow, classifyTrap, DURATIONS, MAX_CHANNELS, FLEET_CAP } = ws;
assert.equal(typeof freqToChannel, 'function', 'wifiScan.js no longer exports freqToChannel');

const FREQS = [
  // 2.4GHz
  2412, 2417, 2437, 2472, 2484, 2400, 2414, 2473, 2477,
  // 5GHz
  5160, 5180, 5500, 5885, 5155, 5163, 5890, 5000,
  // 6GHz — its own base, and tested first
  5955, 5960, 6000, 7115, 5950, 7120, 5957,
  // not frequencies at all
  0, -1, NaN, Infinity, 1.5, 2412.5,
];

const ROWS = [
  ['a full row', { channel: 2437, networks: '3', load: '10', nf: '-95',
                   'max-signal': '-40', 'min-signal': '-80' }],
  ['a compound channel', { channel: '2427/ax/Ce', networks: '1' }],
  ['a compound with no slash parts', { channel: '5180/ac' }],
  ['freq instead of channel', { freq: 5500 }],
  ['both channel and freq — channel wins', { channel: 2412, freq: 5500 }],
  ['a channel that will not parse', { channel: 'abc' }],
  ['an empty channel', { channel: '' }],
  ['a null channel', { channel: null }],
  ['no channel at all', { networks: '2' }],
  ['not an object', 'nope'],
  ['null', null],
  // `_bool` accepts true, 'true' and 'yes' — and nothing else.
  ['primary true', { channel: 2412, primary: true }],
  ['primary "true"', { channel: 2412, primary: 'true' }],
  ['primary "yes"', { channel: 2412, primary: 'yes' }],
  ['primary "1"', { channel: 2412, primary: '1' }],
  ['primary "false"', { channel: 2412, primary: 'false' }],
  ['secondary yes', { channel: 2412, secondary: 'yes' }],
  // `_int` on absent/blank fields is null, not zero — "not reported" and "zero"
  // are different answers on a signal reading.
  ['blank numerics', { channel: 2412, networks: '', load: null, nf: undefined }],
  ['negative signals', { channel: 5180, 'max-signal': '-40', 'min-signal': '-90' }],
  ['a non-numeric load', { channel: 2412, load: 'busy' }],
];

const TRAPS = [
  'not enough privileges',
  'permission denied',
  'cannot run this command',
  'no such command prefix',
  'unknown command',
  'no such item',
  'not found',
  'unknown parameter',
  'no such argument',
  'invalid value',
  'something nobody predicted',
  '',
  null,
  // ORDER: this contains BOTH "no such" and a command phrase. The classifier
  // must call it unsupported-stack, not no-such-interface.
  'no such command prefix (not found)',
  'NOT ENOUGH PRIVILEGES',
];

const cases = {
  durations: DURATIONS,
  maxChannels: MAX_CHANNELS,
  fleetCap: FLEET_CAP,
  freqs: FREQS.map((mhz) => ({
    mhz: Number.isFinite(mhz) ? mhz : String(mhz),
    ch: freqToChannel(mhz),
  })),
  rows: ROWS.map(([name, r]) => ({ name, row: r, want: parseRow(r) })),
  traps: TRAPS.map((m) => ({ msg: m, code: classifyTrap(m) })),
};

// ---- BELIEVABILITY --------------------------------------------------------
{
  const ch = (m) => cases.freqs.find((f) => f.mhz === m).ch;
  assert.equal(ch(2412), 1, '2412 MHz is channel 1');
  assert.equal(ch(2484), 14, '2484 MHz is channel 14');
  assert.equal(ch(5180), 36, '5180 MHz is channel 36');
  assert.equal(ch(5955), 1, '5955 MHz is 6GHz channel 1 — the 6GHz base is not being used');
  assert.equal(ch(5163), null, '5163 MHz is off the /5 grid and must have no channel');
  assert.ok(cases.freqs.filter((f) => f.ch === null).length >= 8,
    'too few frequencies were refused — the grid and band checks are not exercised');

  const row = (n) => cases.rows.find((r) => r.name === n).want;
  assert.equal(row('a channel that will not parse'), null, 'an unparseable row was not dropped');
  assert.equal(row('a compound channel').ch, 2427, 'the compound channel was not split');
  assert.equal(row('a compound channel').chRaw, '2427/ax/Ce', 'the raw channel was not kept');
  assert.equal(row('blank numerics').nets, null, 'a blank numeric became something other than null');
  assert.equal(row('primary "1"').primary, false, '_bool accepted "1"');
  assert.equal(row('primary "yes"').primary, true, '_bool refused "yes"');

  const code = (m) => cases.traps.find((t) => t.msg === m).code;
  assert.equal(code('no such command prefix (not found)'), 'unsupported-stack',
    'the trap order is wrong: a message naming both reads as a missing interface');
  assert.equal(code('something nobody predicted'), 'router-error', 'the fallback is not reached');
  assert.ok(new Set(cases.traps.map((t) => t.code)).size >= 4,
    'the trap corpus does not discriminate');
}

const FILE = path.join(ROOT, 'testdata', 'wifiscan-cases.json');
const text = JSON.stringify(cases, null, 2) + '\n';
if (process.argv.includes('--check')) {
  const have = fs.existsSync(FILE) ? fs.readFileSync(FILE, 'utf8') : '';
  if (have !== text) {
    console.error('wifiscan-cases: STALE — regenerate with `node tools/wifiscan-cases.js`');
    process.exit(1);
  }
  console.log('wifiscan-cases: ' + cases.freqs.length + ' frequencies, ' + cases.rows.length +
    ' rows, ' + cases.traps.length + ' traps current');
} else {
  fs.writeFileSync(FILE, text);
  console.log('wifiscan-cases: wrote ' + cases.freqs.length + ' frequencies, ' +
    cases.rows.length + ' rows and ' + cases.traps.length + ' traps');
}
