// gridgen writes the TypeScript view of `internal/dashcards`.
//
// ── WHY THIS GENERATOR EXISTS AT ALL ────────────────────────────────────────
//
// `web/src/gen/grid-tables.ts` carried a "do not edit" banner naming a JavaScript
// generator under tools/ that was NOT IN THE REPOSITORY. Its name did not even
// match the glob `tools/verify.sh` uses to find generators, so restoring a file
// under that name would still have been invisible to the build. The table was
// therefore hand-edited under a banner forbidding it, with nothing checking the
// result against the Go maps that held the same facts.
//
// (That filename is deliberately not written here as a path. The citation check
// in internal/verify scans for one and cannot tell a location from the name of
// something absent, so spelling it would fail a check by explaining a gap.)
//
// Same shape as `cmd/pagesgen`, and for the same reason: a generator whose
// source is a committed Go file runs on a clean clone, where the 105 retired
// JavaScript ones read a tree that no longer exists and permanently skip.
//
// ── IT EMITS THE EXISTING SURFACE EXACTLY ───────────────────────────────────
//
// `GridCard`, `COLS`, `ROWS`, `GAP`, `PAD`, `MIN_W`, `MIN_H`, `LS_KEY`,
// `DEFAULT_LAYOUT`, `CARD_LABELS` and `CARD_ROOMS`, because five modules and two
// tests import them. The conversion moves where the facts LIVE; it is not an
// opportunity to reshape what the browser reads, and doing both at once would
// make a rendering difference impossible to attribute.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"mikrodash/internal/dashcards"
)

const outRel = "web/src/gen/grid-tables.ts"

func main() {
	out := flag.String("out", outRel, "file to write")
	check := flag.Bool("check", false, "fail if the committed file is stale instead of writing it")
	flag.Parse()

	body := render()

	if *check {
		have, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gridgen: %s is missing; run `go run ./cmd/gridgen`\n", *out)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(have), bytes.TrimSpace(body)) {
			fmt.Fprintf(os.Stderr, "gridgen: %s is STALE — the card table changed and the "+
				"TypeScript was not regenerated.\nRun: go run ./cmd/gridgen\n", *out)
			os.Exit(1)
		}
		fmt.Printf("gridgen: %s is current (%d cards)\n", *out, len(dashcards.All))
		return
	}

	if err := os.WriteFile(*out, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gridgen:", err)
		os.Exit(1)
	}
	fmt.Printf("gridgen: wrote %s — %d cards\n", *out, len(dashcards.All))
}

func render() []byte {
	var b strings.Builder
	b.WriteString(`// GENERATED by cmd/gridgen — do not edit.
//
// The Dashboard grid's tables, from internal/dashcards. That package is the one
// declaration of what a card is: its position, its label, the room it joins and
// the page that gates it. This file is the browser's view of it, and ` + "`-check`" + `
// runs in tools/verify.sh.
//
// It replaced a hand-maintained file naming a generator that was not in the
// repository — so the Go maps it had to agree with were checked by nothing.

export interface GridCard {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  visible: boolean;
}

`)
	fmt.Fprintf(&b, "export const COLS = %d;\n", dashcards.Cols)
	fmt.Fprintf(&b, "export const ROWS = %d;\n", dashcards.Rows)
	fmt.Fprintf(&b, "export const GAP = %d;\n", dashcards.Gap)
	fmt.Fprintf(&b, "export const PAD = %d;\n", dashcards.Pad)
	fmt.Fprintf(&b, "export const MIN_W = %d;\n", dashcards.MinW)
	fmt.Fprintf(&b, "export const MIN_H = %d;\n", dashcards.MinH)

	b.WriteString(`
/** Bumped only on a breaking change to the stored card-object format. */
`)
	fmt.Fprintf(&b, "export const LS_KEY = %s;\n\n", strconv.Quote(dashcards.LSKey))

	b.WriteString("export const DEFAULT_LAYOUT: readonly GridCard[] = [\n")
	for i, c := range dashcards.All {
		comma := ","
		if i == len(dashcards.All)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "  {\n    \"id\": %s,\n    \"x\": %d,\n    \"y\": %d,\n"+
			"    \"w\": %d,\n    \"h\": %d,\n    \"visible\": %t\n  }%s\n",
			strconv.Quote(c.ID), c.X, c.Y, c.W, c.H, c.Visible, comma)
	}
	b.WriteString("];\n\nexport const CARD_LABELS: Readonly<Record<string, string>> = {\n")
	for i, c := range dashcards.All {
		comma := ","
		if i == len(dashcards.All)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "  %s: %s%s\n", strconv.Quote(c.ID), strconv.Quote(c.Label), comma)
	}
	b.WriteString(`};

/**
 * Cards that need a backend room. TWO CARDS CAN SHARE ONE, so leaving a room
 * must be decided by whether ANY visible card still wants it.
 */
export const CARD_ROOMS: Readonly<Record<string, string>> = {
`)
	var rooms []string
	for _, c := range dashcards.All {
		if c.Room != "" {
			rooms = append(rooms, fmt.Sprintf("  %s: %s",
				strconv.Quote(c.ID), strconv.Quote(c.Room)))
		}
	}
	b.WriteString(strings.Join(rooms, ",\n"))
	b.WriteString("\n};\n")
	return []byte(b.String())
}
